/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2022-11-15 09:20:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class blog_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	String pjName = "/KITEN";

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("<title>Aroma Shop - Blog</title>\r\n");
      out.write("<link rel=\"icon\" href=\"");
      out.print(pjName);
      out.write("/resources/img/Fevicon.png\" type=\"image/png\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(pjName);
      out.write("/resources/vendors/bootstrap/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(pjName);
      out.write("/resources/vendors/fontawesome/css/all.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(pjName);
      out.write("/resources/vendors/themify-icons/themify-icons.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(pjName);
      out.write("/resources/vendors/linericon/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(pjName);
      out.write("/resources/vendors/owl-carousel/owl.theme.default.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(pjName);
      out.write("/resources/vendors/owl-carousel/owl.carousel.min.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(pjName);
      out.write("/resources/css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!--================ Start Header Menu Area =================-->\r\n");
      out.write("	<header class=\"header_area\">\r\n");
      out.write("		<div class=\"main_menu\">\r\n");
      out.write("			<nav class=\"navbar navbar-expand-lg navbar-light\">\r\n");
      out.write("				<div class=\"container\">\r\n");
      out.write("					<a class=\"navbar-brand logo_h\" href=\"index.html\"><img src=\"");
      out.print(pjName);
      out.write("/resources/img/logo.png\" alt=\"\"></a>\r\n");
      out.write("					<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
      out.write("						aria-label=\"Toggle navigation\">\r\n");
      out.write("						<span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span>\r\n");
      out.write("					</button>\r\n");
      out.write("					<div class=\"collapse navbar-collapse offset\" id=\"navbarSupportedContent\">\r\n");
      out.write("						<ul class=\"nav navbar-nav menu_nav ml-auto mr-auto\">\r\n");
      out.write("							<li class=\"nav-item\"><a class=\"nav-link\" href=\"index.html\">Home</a></li>\r\n");
      out.write("							<li class=\"nav-item submenu dropdown\"><a href=\"#\" class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">Shop</a>\r\n");
      out.write("								<ul class=\"dropdown-menu\">\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"category.html\">Shop Category</a></li>\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"single-product.html\">Product Details</a></li>\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"checkout.html\">Product Checkout</a></li>\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"confirmation.html\">Confirmation</a></li>\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"cart.html\">Shopping Cart</a></li>\r\n");
      out.write("								</ul></li>\r\n");
      out.write("							<li class=\"nav-item active submenu dropdown\"><a href=\"#\" class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">Blog</a>\r\n");
      out.write("								<ul class=\"dropdown-menu\">\r\n");
      out.write("									<li class=\"nav-item active\"><a class=\"nav-link\" href=\"blog.html\">Blog Single</a></li>\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"single-blog.html\">Blog Details</a></li>\r\n");
      out.write("								</ul></li>\r\n");
      out.write("							<li class=\"nav-item submenu dropdown\"><a href=\"#\" class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">Pages</a>\r\n");
      out.write("								<ul class=\"dropdown-menu\">\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"login.html\">Login</a></li>\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"register.html\">Register</a></li>\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"tracking-order.html\">Tracking</a></li>\r\n");
      out.write("								</ul></li>\r\n");
      out.write("							<li class=\"nav-item\"><a class=\"nav-link\" href=\"contact.html\">Contact</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("\r\n");
      out.write("						<ul class=\"nav-shop\">\r\n");
      out.write("							<li class=\"nav-item\"><button>\r\n");
      out.write("									<i class=\"ti-search\"></i>\r\n");
      out.write("								</button></li>\r\n");
      out.write("							<li class=\"nav-item\"><button>\r\n");
      out.write("									<i class=\"ti-shopping-cart\"></i><span class=\"nav-shop__circle\">3</span>\r\n");
      out.write("								</button></li>\r\n");
      out.write("							<li class=\"nav-item\"><a class=\"button button-header\" href=\"#\">Buy Now</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</nav>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("	<!--================ End Header Menu Area =================-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- ================ start banner area ================= -->\r\n");
      out.write("	<section class=\"blog-banner-area\" id=\"blog\">\r\n");
      out.write("		<div class=\"container h-100\">\r\n");
      out.write("			<div class=\"blog-banner\">\r\n");
      out.write("				<div class=\"text-center\">\r\n");
      out.write("					<h1>Our Blog</h1>\r\n");
      out.write("					<nav aria-label=\"breadcrumb\" class=\"banner-breadcrumb\">\r\n");
      out.write("						<ol class=\"breadcrumb\">\r\n");
      out.write("							<li class=\"breadcrumb-item\"><a href=\"#\">Home</a></li>\r\n");
      out.write("							<li class=\"breadcrumb-item active\" aria-current=\"page\">Blog</li>\r\n");
      out.write("						</ol>\r\n");
      out.write("					</nav>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<!-- ================ end banner area ================= -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!--================Blog Categorie Area =================-->\r\n");
      out.write("	<section class=\"blog_categorie_area\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-sm-6 col-lg-4 mb-4 mb-lg-0\">\r\n");
      out.write("					<div class=\"categories_post\">\r\n");
      out.write("						<img class=\"card-img rounded-0\" src=\"");
      out.print(pjName);
      out.write("/resources/img/blog/cat-post/cat-post-3.jpg\" alt=\"post\">\r\n");
      out.write("						<div class=\"categories_details\">\r\n");
      out.write("							<div class=\"categories_text\">\r\n");
      out.write("								<a href=\"single-blog.html\">\r\n");
      out.write("									<h5>Social Life</h5>\r\n");
      out.write("								</a>\r\n");
      out.write("								<div class=\"border_line\"></div>\r\n");
      out.write("								<p>Enjoy your social life together</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-sm-6 col-lg-4 mb-4 mb-lg-0\">\r\n");
      out.write("					<div class=\"categories_post\">\r\n");
      out.write("						<img class=\"card-img rounded-0\" src=\"");
      out.print(pjName);
      out.write("/resources/img/blog/cat-post/cat-post-2.jpg\" alt=\"post\">\r\n");
      out.write("						<div class=\"categories_details\">\r\n");
      out.write("							<div class=\"categories_text\">\r\n");
      out.write("								<a href=\"single-blog.html\">\r\n");
      out.write("									<h5>Politics</h5>\r\n");
      out.write("								</a>\r\n");
      out.write("								<div class=\"border_line\"></div>\r\n");
      out.write("								<p>Be a part of politics</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-sm-6 col-lg-4 mb-4 mb-lg-0\">\r\n");
      out.write("					<div class=\"categories_post\">\r\n");
      out.write("						<img class=\"card-img rounded-0\" src=\"");
      out.print(pjName);
      out.write("/resources/img/blog/cat-post/cat-post-1.jpg\" alt=\"post\">\r\n");
      out.write("						<div class=\"categories_details\">\r\n");
      out.write("							<div class=\"categories_text\">\r\n");
      out.write("								<a href=\"single-blog.html\">\r\n");
      out.write("									<h5>Food</h5>\r\n");
      out.write("								</a>\r\n");
      out.write("								<div class=\"border_line\"></div>\r\n");
      out.write("								<p>Let the food be finished</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<!--================Blog Categorie Area =================-->\r\n");
      out.write("\r\n");
      out.write("	<!--================Blog Area =================-->\r\n");
      out.write("	<section class=\"blog_area\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-lg-8\">\r\n");
      out.write("					<div class=\"blog_left_sidebar\">\r\n");
      out.write("						<article class=\"row blog_item\">\r\n");
      out.write("							<div class=\"col-md-3\">\r\n");
      out.write("								<div class=\"blog_info text-right\">\r\n");
      out.write("									<div class=\"post_tag\">\r\n");
      out.write("										<a href=\"#\">Food,</a> <a class=\"active\" href=\"#\">Technology,</a> <a href=\"#\">Politics,</a> <a href=\"#\">Lifestyle</a>\r\n");
      out.write("									</div>\r\n");
      out.write("									<ul class=\"blog_meta list\">\r\n");
      out.write("										<li><a href=\"#\">Mark wiens <i class=\"lnr lnr-user\"></i>\r\n");
      out.write("										</a></li>\r\n");
      out.write("										<li><a href=\"#\">12 Dec, 2017 <i class=\"lnr lnr-calendar-full\"></i>\r\n");
      out.write("										</a></li>\r\n");
      out.write("										<li><a href=\"#\">1.2M Views <i class=\"lnr lnr-eye\"></i>\r\n");
      out.write("										</a></li>\r\n");
      out.write("										<li><a href=\"#\">06 Comments <i class=\"lnr lnr-bubble\"></i>\r\n");
      out.write("										</a></li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-md-9\">\r\n");
      out.write("								<div class=\"blog_post\">\r\n");
      out.write("									<img src=\"");
      out.print(pjName);
      out.write("/resources/img/blog/main-blog/m-blog-1.jpg\" alt=\"\">\r\n");
      out.write("									<div class=\"blog_details\">\r\n");
      out.write("										<a href=\"single-blog.html\">\r\n");
      out.write("											<h2>Astronomy Binoculars A Great Alternative</h2>\r\n");
      out.write("										</a>\r\n");
      out.write("										<p>MCSE boot camps have its supporters and its detractors. Some people do not understand why you should have to spend money on boot camp when you can get the MCSE study materials\r\n");
      out.write("											yourself at a fraction.</p>\r\n");
      out.write("										<a class=\"button button-blog\" href=\"single-blog.html\">View More</a>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</article>\r\n");
      out.write("						<article class=\"row blog_item\">\r\n");
      out.write("							<div class=\"col-md-3\">\r\n");
      out.write("								<div class=\"blog_info text-right\">\r\n");
      out.write("									<div class=\"post_tag\">\r\n");
      out.write("										<a href=\"#\">Food,</a> <a class=\"active\" href=\"#\">Technology,</a> <a href=\"#\">Politics,</a> <a href=\"#\">Lifestyle</a>\r\n");
      out.write("									</div>\r\n");
      out.write("									<ul class=\"blog_meta list\">\r\n");
      out.write("										<li><a href=\"#\">Mark wiens <i class=\"lnr lnr-user\"></i>\r\n");
      out.write("										</a></li>\r\n");
      out.write("										<li><a href=\"#\">12 Dec, 2017 <i class=\"lnr lnr-calendar-full\"></i>\r\n");
      out.write("										</a></li>\r\n");
      out.write("										<li><a href=\"#\">1.2M Views <i class=\"lnr lnr-eye\"></i>\r\n");
      out.write("										</a></li>\r\n");
      out.write("										<li><a href=\"#\">06 Comments <i class=\"lnr lnr-bubble\"></i>\r\n");
      out.write("										</a></li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-md-9\">\r\n");
      out.write("								<div class=\"blog_post\">\r\n");
      out.write("									<img src=\"");
      out.print(pjName);
      out.write("/resources/img/blog/main-blog/m-blog-2.jpg\" alt=\"\">\r\n");
      out.write("									<div class=\"blog_details\">\r\n");
      out.write("										<a href=\"single-blog.html\">\r\n");
      out.write("											<h2>The Basics Of Buying A Telescope</h2>\r\n");
      out.write("										</a>\r\n");
      out.write("										<p>MCSE boot camps have its supporters and its detractors. Some people do not understand why you should have to spend money on boot camp when you can get the MCSE study materials\r\n");
      out.write("											yourself at a fraction.</p>\r\n");
      out.write("										<a href=\"single-blog.html\" class=\"button button-blog\">View More</a>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</article>\r\n");
      out.write("						<article class=\"row blog_item\">\r\n");
      out.write("							<div class=\"col-md-3\">\r\n");
      out.write("								<div class=\"blog_info text-right\">\r\n");
      out.write("									<div class=\"post_tag\">\r\n");
      out.write("										<a href=\"#\">Food,</a> <a class=\"active\" href=\"#\">Technology,</a> <a href=\"#\">Politics,</a> <a href=\"#\">Lifestyle</a>\r\n");
      out.write("									</div>\r\n");
      out.write("									<ul class=\"blog_meta list\">\r\n");
      out.write("										<li><a href=\"#\">Mark wiens <i class=\"lnr lnr-user\"></i>\r\n");
      out.write("										</a></li>\r\n");
      out.write("										<li><a href=\"#\">12 Dec, 2017 <i class=\"lnr lnr-calendar-full\"></i>\r\n");
      out.write("										</a></li>\r\n");
      out.write("										<li><a href=\"#\">1.2M Views <i class=\"lnr lnr-eye\"></i>\r\n");
      out.write("										</a></li>\r\n");
      out.write("										<li><a href=\"#\">06 Comments <i class=\"lnr lnr-bubble\"></i>\r\n");
      out.write("										</a></li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-md-9\">\r\n");
      out.write("								<div class=\"blog_post\">\r\n");
      out.write("									<img src=\"");
      out.print(pjName);
      out.write("/resources/img/blog/main-blog/m-blog-3.jpg\" alt=\"\">\r\n");
      out.write("									<div class=\"blog_details\">\r\n");
      out.write("										<a href=\"single-blog.html\">\r\n");
      out.write("											<h2>The Glossary Of Telescopes</h2>\r\n");
      out.write("										</a>\r\n");
      out.write("										<p>MCSE boot camps have its supporters and its detractors. Some people do not understand why you should have to spend money on boot camp when you can get the MCSE study materials\r\n");
      out.write("											yourself at a fraction.</p>\r\n");
      out.write("										<a href=\"single-blog.html\" class=\"button button-blog\">View More</a>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</article>\r\n");
      out.write("						<article class=\"row blog_item\">\r\n");
      out.write("							<div class=\"col-md-3\">\r\n");
      out.write("								<div class=\"blog_info text-right\">\r\n");
      out.write("									<div class=\"post_tag\">\r\n");
      out.write("										<a href=\"#\">Food,</a> <a class=\"active\" href=\"#\">Technology,</a> <a href=\"#\">Politics,</a> <a href=\"#\">Lifestyle</a>\r\n");
      out.write("									</div>\r\n");
      out.write("									<ul class=\"blog_meta list\">\r\n");
      out.write("										<li><a href=\"#\">Mark wiens <i class=\"lnr lnr-user\"></i>\r\n");
      out.write("										</a></li>\r\n");
      out.write("										<li><a href=\"#\">12 Dec, 2017 <i class=\"lnr lnr-calendar-full\"></i>\r\n");
      out.write("										</a></li>\r\n");
      out.write("										<li><a href=\"#\">1.2M Views <i class=\"lnr lnr-eye\"></i>\r\n");
      out.write("										</a></li>\r\n");
      out.write("										<li><a href=\"#\">06 Comments <i class=\"lnr lnr-bubble\"></i>\r\n");
      out.write("										</a></li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-md-9\">\r\n");
      out.write("								<div class=\"blog_post\">\r\n");
      out.write("									<img src=\"");
      out.print(pjName);
      out.write("/resources/img/blog/main-blog/m-blog-4.jpg\" alt=\"\">\r\n");
      out.write("									<div class=\"blog_details\">\r\n");
      out.write("										<a href=\"single-blog.html\">\r\n");
      out.write("											<h2>The Night Sky</h2>\r\n");
      out.write("										</a>\r\n");
      out.write("										<p>MCSE boot camps have its supporters and its detractors. Some people do not understand why you should have to spend money on boot camp when you can get the MCSE study materials\r\n");
      out.write("											yourself at a fraction.</p>\r\n");
      out.write("										<a href=\"single-blog.html\" class=\"button button-blog\">View More</a>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</article>\r\n");
      out.write("						<article class=\"row blog_item\">\r\n");
      out.write("							<div class=\"col-md-3\">\r\n");
      out.write("								<div class=\"blog_info text-right\">\r\n");
      out.write("									<div class=\"post_tag\">\r\n");
      out.write("										<a href=\"#\">Food,</a> <a class=\"active\" href=\"#\">Technology,</a> <a href=\"#\">Politics,</a> <a href=\"#\">Lifestyle</a>\r\n");
      out.write("									</div>\r\n");
      out.write("									<ul class=\"blog_meta list\">\r\n");
      out.write("										<li><a href=\"#\">Mark wiens <i class=\"lnr lnr-user\"></i>\r\n");
      out.write("										</a></li>\r\n");
      out.write("										<li><a href=\"#\">12 Dec, 2017 <i class=\"lnr lnr-calendar-full\"></i>\r\n");
      out.write("										</a></li>\r\n");
      out.write("										<li><a href=\"#\">1.2M Views <i class=\"lnr lnr-eye\"></i>\r\n");
      out.write("										</a></li>\r\n");
      out.write("										<li><a href=\"#\">06 Comments <i class=\"lnr lnr-bubble\"></i>\r\n");
      out.write("										</a></li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-md-9\">\r\n");
      out.write("								<div class=\"blog_post\">\r\n");
      out.write("									<img src=\"");
      out.print(pjName);
      out.write("/resources/img/blog/main-blog/m-blog-5.jpg\" alt=\"\">\r\n");
      out.write("									<div class=\"blog_details\">\r\n");
      out.write("										<a href=\"single-blog.html\">\r\n");
      out.write("											<h2>Telescopes 101</h2>\r\n");
      out.write("										</a>\r\n");
      out.write("										<p>MCSE boot camps have its supporters and its detractors. Some people do not understand why you should have to spend money on boot camp when you can get the MCSE study materials\r\n");
      out.write("											yourself at a fraction.</p>\r\n");
      out.write("										<a href=\"single-blog.html\" class=\"button button-blog\">View More</a>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</article>\r\n");
      out.write("						<nav class=\"blog-pagination justify-content-center d-flex\">\r\n");
      out.write("							<ul class=\"pagination\">\r\n");
      out.write("								<li class=\"page-item\"><a href=\"#\" class=\"page-link\" aria-label=\"Previous\"> <span aria-hidden=\"true\"> <span class=\"lnr lnr-chevron-left\"></span>\r\n");
      out.write("									</span>\r\n");
      out.write("								</a></li>\r\n");
      out.write("								<li class=\"page-item\"><a href=\"#\" class=\"page-link\">01</a></li>\r\n");
      out.write("								<li class=\"page-item active\"><a href=\"#\" class=\"page-link\">02</a></li>\r\n");
      out.write("								<li class=\"page-item\"><a href=\"#\" class=\"page-link\">03</a></li>\r\n");
      out.write("								<li class=\"page-item\"><a href=\"#\" class=\"page-link\">04</a></li>\r\n");
      out.write("								<li class=\"page-item\"><a href=\"#\" class=\"page-link\">09</a></li>\r\n");
      out.write("								<li class=\"page-item\"><a href=\"#\" class=\"page-link\" aria-label=\"Next\"> <span aria-hidden=\"true\"> <span class=\"lnr lnr-chevron-right\"></span>\r\n");
      out.write("									</span>\r\n");
      out.write("								</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</nav>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-4\">\r\n");
      out.write("					<div class=\"blog_right_sidebar\">\r\n");
      out.write("						<aside class=\"single_sidebar_widget search_widget\">\r\n");
      out.write("							<div class=\"input-group\">\r\n");
      out.write("								<input type=\"text\" class=\"form-control\" placeholder=\"Search Posts\"> <span class=\"input-group-btn\">\r\n");
      out.write("									<button class=\"btn btn-default\" type=\"button\">\r\n");
      out.write("										<i class=\"lnr lnr-magnifier\"></i>\r\n");
      out.write("									</button>\r\n");
      out.write("								</span>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- /input-group -->\r\n");
      out.write("							<div class=\"br\"></div>\r\n");
      out.write("						</aside>\r\n");
      out.write("						<aside class=\"single_sidebar_widget author_widget\">\r\n");
      out.write("							<img class=\"author_img rounded-circle\" src=\"");
      out.print(pjName);
      out.write("/resources/img/blog/author.png\" alt=\"\">\r\n");
      out.write("							<h4>Charlie Barber</h4>\r\n");
      out.write("							<p>Senior blog writer</p>\r\n");
      out.write("							<div class=\"social_icon\">\r\n");
      out.write("								<a href=\"#\"> <i class=\"fab fa-facebook-f\"></i>\r\n");
      out.write("								</a> <a href=\"#\"> <i class=\"fab fa-twitter\"></i>\r\n");
      out.write("								</a> <a href=\"#\"> <i class=\"fab fa-github\"></i>\r\n");
      out.write("								</a> <a href=\"#\"> <i class=\"fab fa-behance\"></i>\r\n");
      out.write("								</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<p>Boot camps have its supporters andit sdetractors. Some people do not understand why you should have to spend money on boot camp when you can get. Boot camps have itssuppor ters andits\r\n");
      out.write("								detractors.</p>\r\n");
      out.write("							<div class=\"br\"></div>\r\n");
      out.write("						</aside>\r\n");
      out.write("						<aside class=\"single_sidebar_widget popular_post_widget\">\r\n");
      out.write("							<h3 class=\"widget_title\">Popular Posts</h3>\r\n");
      out.write("							<div class=\"media post_item\">\r\n");
      out.write("								<img src=\"");
      out.print(pjName);
      out.write("/resources/img/blog/popular-post/post1.jpg\" alt=\"post\">\r\n");
      out.write("								<div class=\"media-body\">\r\n");
      out.write("									<a href=\"single-blog.html\">\r\n");
      out.write("										<h3>Space The Final Frontier</h3>\r\n");
      out.write("									</a>\r\n");
      out.write("									<p>02 Hours ago</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"media post_item\">\r\n");
      out.write("								<img src=\"");
      out.print(pjName);
      out.write("/resources/img/blog/popular-post/post2.jpg\" alt=\"post\">\r\n");
      out.write("								<div class=\"media-body\">\r\n");
      out.write("									<a href=\"single-blog.html\">\r\n");
      out.write("										<h3>The Amazing Hubble</h3>\r\n");
      out.write("									</a>\r\n");
      out.write("									<p>02 Hours ago</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"media post_item\">\r\n");
      out.write("								<img src=\"");
      out.print(pjName);
      out.write("/resources/img/blog/popular-post/post3.jpg\" alt=\"post\">\r\n");
      out.write("								<div class=\"media-body\">\r\n");
      out.write("									<a href=\"single-blog.html\">\r\n");
      out.write("										<h3>Astronomy Or Astrology</h3>\r\n");
      out.write("									</a>\r\n");
      out.write("									<p>03 Hours ago</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"media post_item\">\r\n");
      out.write("								<img src=\"");
      out.print(pjName);
      out.write("/resources/img/blog/popular-post/post4.jpg\" alt=\"post\">\r\n");
      out.write("								<div class=\"media-body\">\r\n");
      out.write("									<a href=\"single-blog.html\">\r\n");
      out.write("										<h3>Asteroids telescope</h3>\r\n");
      out.write("									</a>\r\n");
      out.write("									<p>01 Hours ago</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"br\"></div>\r\n");
      out.write("						</aside>\r\n");
      out.write("						<aside class=\"single_sidebar_widget ads_widget\">\r\n");
      out.write("							<a href=\"#\"> <img class=\"img-fluid\" src=\"");
      out.print(pjName);
      out.write("/resources/img/blog/add.jpg\" alt=\"\">\r\n");
      out.write("							</a>\r\n");
      out.write("							<div class=\"br\"></div>\r\n");
      out.write("						</aside>\r\n");
      out.write("						<aside class=\"single_sidebar_widget post_category_widget\">\r\n");
      out.write("							<h4 class=\"widget_title\">Post Catgories</h4>\r\n");
      out.write("							<ul class=\"list cat-list\">\r\n");
      out.write("								<li><a href=\"#\" class=\"d-flex justify-content-between\">\r\n");
      out.write("										<p>Technology</p>\r\n");
      out.write("										<p>37</p>\r\n");
      out.write("								</a></li>\r\n");
      out.write("								<li><a href=\"#\" class=\"d-flex justify-content-between\">\r\n");
      out.write("										<p>Lifestyle</p>\r\n");
      out.write("										<p>24</p>\r\n");
      out.write("								</a></li>\r\n");
      out.write("								<li><a href=\"#\" class=\"d-flex justify-content-between\">\r\n");
      out.write("										<p>Fashion</p>\r\n");
      out.write("										<p>59</p>\r\n");
      out.write("								</a></li>\r\n");
      out.write("								<li><a href=\"#\" class=\"d-flex justify-content-between\">\r\n");
      out.write("										<p>Art</p>\r\n");
      out.write("										<p>29</p>\r\n");
      out.write("								</a></li>\r\n");
      out.write("								<li><a href=\"#\" class=\"d-flex justify-content-between\">\r\n");
      out.write("										<p>Food</p>\r\n");
      out.write("										<p>15</p>\r\n");
      out.write("								</a></li>\r\n");
      out.write("								<li><a href=\"#\" class=\"d-flex justify-content-between\">\r\n");
      out.write("										<p>Architecture</p>\r\n");
      out.write("										<p>09</p>\r\n");
      out.write("								</a></li>\r\n");
      out.write("								<li><a href=\"#\" class=\"d-flex justify-content-between\">\r\n");
      out.write("										<p>Adventure</p>\r\n");
      out.write("										<p>44</p>\r\n");
      out.write("								</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("							<div class=\"br\"></div>\r\n");
      out.write("						</aside>\r\n");
      out.write("						<aside class=\"single-sidebar-widget newsletter_widget\">\r\n");
      out.write("							<h4 class=\"widget_title\">Newsletter</h4>\r\n");
      out.write("							<p>Here, I focus on a range of items and features that we use in life without giving them a second thought.</p>\r\n");
      out.write("							<div class=\"form-group d-flex flex-row\">\r\n");
      out.write("								<div class=\"input-group\">\r\n");
      out.write("									<div class=\"input-group-prepend\">\r\n");
      out.write("										<div class=\"input-group-text\">\r\n");
      out.write("											<i class=\"fa fa-envelope\" aria-hidden=\"true\"></i>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<input type=\"text\" class=\"form-control\" id=\"inlineFormInputGroup\" placeholder=\"Enter email address\" onfocus=\"this.placeholder = ''\" onblur=\"this.placeholder = 'Enter email'\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<a href=\"#\" class=\"bbtns\">Subcribe</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<p class=\"text-bottom\">You can unsubscribe at any time</p>\r\n");
      out.write("							<div class=\"br\"></div>\r\n");
      out.write("						</aside>\r\n");
      out.write("						<aside class=\"single-sidebar-widget tag_cloud_widget\">\r\n");
      out.write("							<h4 class=\"widget_title\">Tag Clouds</h4>\r\n");
      out.write("							<ul class=\"list\">\r\n");
      out.write("								<li><a href=\"#\">Technology</a></li>\r\n");
      out.write("								<li><a href=\"#\">Fashion</a></li>\r\n");
      out.write("								<li><a href=\"#\">Architecture</a></li>\r\n");
      out.write("								<li><a href=\"#\">Fashion</a></li>\r\n");
      out.write("								<li><a href=\"#\">Food</a></li>\r\n");
      out.write("								<li><a href=\"#\">Technology</a></li>\r\n");
      out.write("								<li><a href=\"#\">Lifestyle</a></li>\r\n");
      out.write("								<li><a href=\"#\">Art</a></li>\r\n");
      out.write("								<li><a href=\"#\">Adventure</a></li>\r\n");
      out.write("								<li><a href=\"#\">Food</a></li>\r\n");
      out.write("								<li><a href=\"#\">Lifestyle</a></li>\r\n");
      out.write("								<li><a href=\"#\">Adventure</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</aside>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<!--================Blog Area =================-->\r\n");
      out.write("\r\n");
      out.write("	<!--================Instagram Area =================-->\r\n");
      out.write("	<section class=\"instagram_area\">\r\n");
      out.write("		<div class=\"container box_1620\">\r\n");
      out.write("			<div class=\"insta_btn\">\r\n");
      out.write("				<a class=\"btn theme_btn\" href=\"#\">Follow us on instagram</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"instagram_image row m0\">\r\n");
      out.write("				<a href=\"#\"><img src=\"");
      out.print(pjName);
      out.write("/resources/img/instagram/ins-1.jpg\" alt=\"\"></a> <a href=\"#\"><img src=\"");
      out.print(pjName);
      out.write("/resources/img/instagram/ins-2.jpg\" alt=\"\"></a> <a href=\"#\"><img src=\"");
      out.print(pjName);
      out.write("/resources/img/instagram/ins-3.jpg\" alt=\"\"></a> <a\r\n");
      out.write("					href=\"#\"><img src=\"");
      out.print(pjName);
      out.write("/resources/img/instagram/ins-4.jpg\" alt=\"\"></a> <a href=\"#\"><img src=\"");
      out.print(pjName);
      out.write("/resources/img/instagram/ins-5.jpg\" alt=\"\"></a> <a href=\"#\"><img src=\"");
      out.print(pjName);
      out.write("/resources/img/instagram/ins-6.jpg\" alt=\"\"></a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<!--================End Instagram Area =================-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!--================ Start footer Area  =================-->\r\n");
      out.write("	<footer>\r\n");
      out.write("		<div class=\"footer-area\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row section_gap\">\r\n");
      out.write("					<div class=\"col-lg-3 col-md-6 col-sm-6\">\r\n");
      out.write("						<div class=\"single-footer-widget tp_widgets\">\r\n");
      out.write("							<h4 class=\"footer_title large_title\">Our Mission</h4>\r\n");
      out.write("							<p>So seed seed green that winged cattle in. Gathering thing made fly you're no divided deep moved us lan Gathering thing us land years living.</p>\r\n");
      out.write("							<p>So seed seed green that winged cattle in. Gathering thing made fly you're no divided deep moved</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"offset-lg-1 col-lg-2 col-md-6 col-sm-6\">\r\n");
      out.write("						<div class=\"single-footer-widget tp_widgets\">\r\n");
      out.write("							<h4 class=\"footer_title\">Quick Links</h4>\r\n");
      out.write("							<ul class=\"list\">\r\n");
      out.write("								<li><a href=\"#\">Home</a></li>\r\n");
      out.write("								<li><a href=\"#\">Shop</a></li>\r\n");
      out.write("								<li><a href=\"#\">Blog</a></li>\r\n");
      out.write("								<li><a href=\"#\">Product</a></li>\r\n");
      out.write("								<li><a href=\"#\">Brand</a></li>\r\n");
      out.write("								<li><a href=\"#\">Contact</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-lg-2 col-md-6 col-sm-6\">\r\n");
      out.write("						<div class=\"single-footer-widget instafeed\">\r\n");
      out.write("							<h4 class=\"footer_title\">Gallery</h4>\r\n");
      out.write("							<ul class=\"list instafeed d-flex flex-wrap\">\r\n");
      out.write("								<li><img src=\"");
      out.print(pjName);
      out.write("/resources/img/gallery/r1.jpg\" alt=\"\"></li>\r\n");
      out.write("								<li><img src=\"");
      out.print(pjName);
      out.write("/resources/img/gallery/r2.jpg\" alt=\"\"></li>\r\n");
      out.write("								<li><img src=\"");
      out.print(pjName);
      out.write("/resources/img/gallery/r3.jpg\" alt=\"\"></li>\r\n");
      out.write("								<li><img src=\"");
      out.print(pjName);
      out.write("/resources/img/gallery/r5.jpg\" alt=\"\"></li>\r\n");
      out.write("								<li><img src=\"");
      out.print(pjName);
      out.write("/resources/img/gallery/r7.jpg\" alt=\"\"></li>\r\n");
      out.write("								<li><img src=\"");
      out.print(pjName);
      out.write("/resources/img/gallery/r8.jpg\" alt=\"\"></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"offset-lg-1 col-lg-3 col-md-6 col-sm-6\">\r\n");
      out.write("						<div class=\"single-footer-widget tp_widgets\">\r\n");
      out.write("							<h4 class=\"footer_title\">Contact Us</h4>\r\n");
      out.write("							<div class=\"ml-40\">\r\n");
      out.write("								<p class=\"sm-head\">\r\n");
      out.write("									<span class=\"fa fa-location-arrow\"></span> Head Office\r\n");
      out.write("								</p>\r\n");
      out.write("								<p>123, Main Street, Your City</p>\r\n");
      out.write("\r\n");
      out.write("								<p class=\"sm-head\">\r\n");
      out.write("									<span class=\"fa fa-phone\"></span> Phone Number\r\n");
      out.write("								</p>\r\n");
      out.write("								<p>\r\n");
      out.write("									+123 456 7890 <br> +123 456 7890\r\n");
      out.write("								</p>\r\n");
      out.write("\r\n");
      out.write("								<p class=\"sm-head\">\r\n");
      out.write("									<span class=\"fa fa-envelope\"></span> Email\r\n");
      out.write("								</p>\r\n");
      out.write("								<p>\r\n");
      out.write("									free@infoexample.com <br> www.infoexample.com\r\n");
      out.write("								</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"footer-bottom\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row d-flex\">\r\n");
      out.write("					<p class=\"col-lg-12 footer-text text-center\">\r\n");
      out.write("						<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("						Copyright &copy;\r\n");
      out.write("						<script>document.write(new Date().getFullYear());</script>\r\n");
      out.write("						All rights reserved | This template is made with <i class=\"fa fa-heart\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\r\n");
      out.write("						<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("					</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("	<!--================ End footer Area  =================-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script src=\"");
      out.print(pjName);
      out.write("/resources/vendors/jquery/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.print(pjName);
      out.write("/resources/vendors/bootstrap/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.print(pjName);
      out.write("/resources/vendors/skrollr.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.print(pjName);
      out.write("/resources/vendors/owl-carousel/owl.carousel.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.print(pjName);
      out.write("/resources/vendors/nice-select/jquery.nice-select.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.print(pjName);
      out.write("/resources/vendors/jquery.ajaxchimp.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.print(pjName);
      out.write("/resources/vendors/mail-script.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.print(pjName);
      out.write("/resources/js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
