/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2022-11-25 09:18:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/semiProject_KITEN/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/KITEN/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1668046159892L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
 String pjName = "/KITEN"; 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("<title>요리하는 고양이, KITEN</title>\r\n");
      out.write("<!-- 상단에 이름이랑 같이 뜨는 이미지 -->\r\n");
      out.write("<link rel=\"icon\" href=\"");
      out.print(pjName);
      out.write("/resources/img/Fevicon.png\" type=\"image/png\">\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link href=\"");
      out.print(pjName);
      out.write("/resources/vendors/bootstrap/bootstrap.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"");
      out.print(pjName);
      out.write("/resources/vendors/fontawesome/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"");
      out.print(pjName);
      out.write("/resources/vendors/themify-icons/themify-icons.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"");
      out.print(pjName);
      out.write("/resources/vendors/nice-select/nice-select.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"");
      out.print(pjName);
      out.write("/resources/vendors/owl-carousel/owl.theme.default.min.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"");
      out.print(pjName);
      out.write("/resources/vendors/owl-carousel/owl.carousel.min.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("<script src=\"//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("  $(document).ready(function(){\r\n");
      out.write("    $('.slider').bxSlider();\r\n");
      out.write("  });\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".bx-wrapper {\r\n");
      out.write("    -moz-box-shadow: 0 0 0px #ccc;\r\n");
      out.write("    -webkit-box-shadow: 0 0 0px #ccc;\r\n");
      out.write("    box-shadow: 0 0 0px #ccc0;\r\n");
      out.write("    }\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(pjName);
      out.write("/resources/css/stylej.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(pjName);
      out.write("/resources/css/footer.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!--================ Start Header Menu Area =================-->\r\n");
      out.write("	<header class=\"header_area\">\r\n");
      out.write("		<div class=\"main_menu\">\r\n");
      out.write("			<nav class=\"navbar navbar-expand-lg navbar-light\">\r\n");
      out.write("				<div class=\"container\">\r\n");
      out.write("					<a class=\"navbar-brand logo_h\" href=\"");
      out.print(pjName);
      out.write("/home.do\"><img src=\"");
      out.print(pjName);
      out.write("/resources/img/logo.png\" alt=\"\"></a>\r\n");
      out.write("					<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
      out.write("						aria-label=\"Toggle navigation\">\r\n");
      out.write("						<span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span>\r\n");
      out.write("					</button>\r\n");
      out.write("					<div class=\"collapse navbar-collapse offset\" id=\"navbarSupportedContent\">\r\n");
      out.write("						<ul class=\"nav navbar-nav menu_nav ml-auto mr-auto\">\r\n");
      out.write("							<li class=\"nav-item submenu dropdown\"><a href=\"#\" class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\"\r\n");
      out.write("								aria-expanded=\"false\">쇼핑하기</a>\r\n");
      out.write("								<ul class=\"dropdown-menu\">\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print(pjName);
      out.write("/product/getProductList.do\">전체 상품 보기</a></li>\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print(pjName);
      out.write("/product/getCategoryList.do?categoryname=한식\">한식</a></li>\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print(pjName);
      out.write("/product/getCategoryList.do?categoryname=중식\">중식</a></li>\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print(pjName);
      out.write("/product/getCategoryList.do?categoryname=일식\">일식</a></li>\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print(pjName);
      out.write("/product/getCategoryList.do?categoryname=양식\">양식</a></li>\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print(pjName);
      out.write("/product/getCategoryList.do?categoryname=동남아\">동남아</a></li>\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print(pjName);
      out.write("/product/getCategoryList.do?categoryname=분식\">분식</a></li>\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print(pjName);
      out.write("/product/getCategoryList.do?categoryname=기타\">기타</a></li>\r\n");
      out.write("								</ul></li>\r\n");
      out.write("							<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">인기 상품</a></li>\r\n");
      out.write("							<li class=\"nav-item submenu dropdown\"><a href=\"#\" class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">고객센터</a>\r\n");
      out.write("								<ul class=\"dropdown-menu\">\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">공지사항</a></li>\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">일대일 문의</a></li>\r\n");
      out.write("								</ul></li>\r\n");
      out.write("							<!-- 로그아웃 시 출력할 헤더 -->\r\n");
      out.write("							");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f0_reused = false;
      try {
        _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f0.setParent(null);
        // /WEB-INF/views/home.jsp(78,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty sessionScope.userId}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
        int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
        if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("								<li class=\"nav-item\"><a class=\"nav-link\" href=\"");
            out.print(pjName);
            out.write("/user/userJoin.do\">회원 가입</a></li>\r\n");
            out.write("								<li class=\"nav-item\"><a class=\"nav-link\" href=\"");
            out.print(pjName);
            out.write("/user/userLogin.do\">로그인</a></li>\r\n");
            out.write("							");
            int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
        _jspx_th_c_005fif_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
      }
      out.write("\r\n");
      out.write("							<!-- 로그인 시 출력할 헤더 -->\r\n");
      out.write("							");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f1_reused = false;
      try {
        _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f1.setParent(null);
        // /WEB-INF/views/home.jsp(83,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty sessionScope.userId}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
        int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
        if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("								<li class=\"nav-item submenu dropdown\"><a href=\"#\" class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">마이 페이지</a>\r\n");
            out.write("									<ul class=\"dropdown-menu\">\r\n");
            out.write("										<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">주문 내역</a></li>\r\n");
            out.write("										<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">찜한 상품</a></li>\r\n");
            out.write("										<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">배송지 관리</a></li>\r\n");
            out.write("										<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">나의 문의</a></li>\r\n");
            out.write("										<li class=\"nav-item\"><a class=\"nav-link\" href=\"");
            out.print(pjName);
            out.write("/user/userModify.do\">회원 정보 수정</a></li>\r\n");
            out.write("										<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">회원 탈퇴</a></li>\r\n");
            out.write("									</ul></li>\r\n");
            out.write("								<li class=\"nav-item\"><a class=\"nav-link\" href=\"");
            out.print(pjName);
            out.write("/user/userLogout.do\">로그아웃</a></li>\r\n");
            out.write("							");
            int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
        _jspx_th_c_005fif_005f1_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
      }
      out.write("\r\n");
      out.write("						</ul>\r\n");
      out.write("\r\n");
      out.write("						<ul class=\"nav-shop\">\r\n");
      out.write("							");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f2_reused = false;
      try {
        _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f2.setParent(null);
        // /WEB-INF/views/home.jsp(98,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty sessionScope.userId}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
        int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
        if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("								<li class=\"nav-item\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("님</li>\r\n");
            out.write("							<li class=\"nav-item\"><button>\r\n");
            out.write("									<i class=\"ti-location-pin\"></i>\r\n");
            out.write("								</button></li>\r\n");
            out.write("							<li class=\"nav-item\"><button>\r\n");
            out.write("									<i class=\"ti-heart\"></i>\r\n");
            out.write("								</button></li>\r\n");
            out.write("							<li class=\"nav-item\"><a href=\"");
            out.print(pjName);
            out.write("/my/cart.do?m_number=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"><button>\r\n");
            out.write("									<i class=\"ti-shopping-cart\"></i><span class=\"nav-shop__circle\">3</span>\r\n");
            out.write("								</button></a></li>\r\n");
            out.write("							");
            int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
        _jspx_th_c_005fif_005f2_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
      }
      out.write("\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</nav>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("	<!--================ End Header Menu Area =================-->\r\n");
      out.write("\r\n");
      out.write("	<main class=\"site-main\">\r\n");
      out.write("\r\n");
      out.write("		<!--================ Hero banner start =================-->\r\n");
      out.write("\r\n");
      out.write("			\r\n");
      out.write("				\r\n");
      out.write("						<br></br>\r\n");
      out.write("						<div class=\"hero-banner__img\">\r\n");
      out.write("						\r\n");
      out.write("							<ul class=\"main_bxslider\">\r\n");
      out.write("							<div class=\"slider\">\r\n");
      out.write("								<img src=\"");
      out.print(pjName);
      out.write("/resources/img/home/main1.png\" /></li>\r\n");
      out.write("								<img src=\"");
      out.print(pjName);
      out.write("/resources/img/home/main2.png\" /></li>\r\n");
      out.write("								<img src=\"");
      out.print(pjName);
      out.write("/resources/img/home/main3.png\" /></li>\r\n");
      out.write("								<img src=\"");
      out.print(pjName);
      out.write("/resources/img/home/main4.png\" /></li>\r\n");
      out.write("								<img src=\"");
      out.print(pjName);
      out.write("/resources/img/home/main5.png\" /></li>\r\n");
      out.write("								<img src=\"");
      out.print(pjName);
      out.write("/resources/img/home/main6.png\" /></li>\r\n");
      out.write("								<img src=\"");
      out.print(pjName);
      out.write("/resources/img/home/main7.png\" /></li>\r\n");
      out.write("							</div>\r\n");
      out.write("							</ul>\r\n");
      out.write("							\r\n");
      out.write("						\r\n");
      out.write("					\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("			\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		<!--================ Hero banner start =================-->\r\n");
      out.write("\r\n");
      out.write("		<!--================ Hero Carousel start =================-->\r\n");
      out.write("		\r\n");
      out.write("		<!--================ Hero Carousel end =================-->\r\n");
      out.write("\r\n");
      out.write("		<!-- ================ trending product section start ================= -->\r\n");
      out.write("		<section class=\"section-margin calc-60px\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"section-intro pb-60px\">\r\n");
      out.write("					<p>새로 들어온 제품들	</p>\r\n");
      out.write("					<h2>\r\n");
      out.write("						주목해야할 <span class=\"section-intro__style\">신상품</span>\r\n");
      out.write("					</h2>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"col-md-6 col-lg-4 col-xl-3\">\r\n");
      out.write("						<div class=\"card text-center card-product\">\r\n");
      out.write("							<div class=\"card-product__img\">\r\n");
      out.write("								<img class=\"card-img\" src=\"/KITEN/resources/upload/b8df79d2-7122-4b0c-a7ab-c5c729d105c8_others_list4.jpg\" alt=\"\">\r\n");
      out.write("								<ul class=\"card-product__imgOverlay\">\r\n");
      out.write("									<li><button>\r\n");
      out.write("											<i class=\"ti-search\"></i>\r\n");
      out.write("										</button></li>\r\n");
      out.write("									<li><button>\r\n");
      out.write("											<i class=\"ti-shopping-cart\"></i>\r\n");
      out.write("										</button></li>\r\n");
      out.write("									<li><button>\r\n");
      out.write("											<i class=\"ti-heart\"></i>\r\n");
      out.write("										</button></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"card-body\">\r\n");
      out.write("								<p>영칼로리</p>\r\n");
      out.write("								<h4 class=\"card-product__title\">\r\n");
      out.write("									<a href=\"single-product.html\">바삭 코코넛 쉬림프(1인)</a>\r\n");
      out.write("								</h4>\r\n");
      out.write("								<p class=\"card-product__price\">7900원</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-md-6 col-lg-4 col-xl-3\">\r\n");
      out.write("						<div class=\"card text-center card-product\">\r\n");
      out.write("							<div class=\"card-product__img\">\r\n");
      out.write("								<img class=\"card-img\" src=\"/KITEN/resources/upload/828cb88b-e03e-480e-aa71-3c545b5e6fc3_others_list3.jpg\" alt=\"\">\r\n");
      out.write("								<ul class=\"card-product__imgOverlay\">\r\n");
      out.write("									<li><button>\r\n");
      out.write("											<i class=\"ti-search\"></i>\r\n");
      out.write("										</button></li>\r\n");
      out.write("									<li><button>\r\n");
      out.write("											<i class=\"ti-shopping-cart\"></i>\r\n");
      out.write("										</button></li>\r\n");
      out.write("									<li><button>\r\n");
      out.write("											<i class=\"ti-heart\"></i>\r\n");
      out.write("										</button></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"card-body\">\r\n");
      out.write("								<p>상현달</p>\r\n");
      out.write("								<h4 class=\"card-product__title\">\r\n");
      out.write("									<a href=\"single-product.html\">모짜렐라 뿌링뿌링 치즈볼(1인)</a>\r\n");
      out.write("								</h4>\r\n");
      out.write("								<p class=\"card-product__price\">6900원</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-md-6 col-lg-4 col-xl-3\">\r\n");
      out.write("						<div class=\"card text-center card-product\">\r\n");
      out.write("							<div class=\"card-product__img\">\r\n");
      out.write("								<img class=\"card-img\" src=\"/KITEN/resources/upload/55fa6d6a-4ff9-436e-90df-9dd0a749e6a8_others_list2.jpg\" alt=\"\">\r\n");
      out.write("								<ul class=\"card-product__imgOverlay\">\r\n");
      out.write("									<li><button>\r\n");
      out.write("											<i class=\"ti-search\"></i>\r\n");
      out.write("										</button></li>\r\n");
      out.write("									<li><button>\r\n");
      out.write("											<i class=\"ti-shopping-cart\"></i>\r\n");
      out.write("										</button></li>\r\n");
      out.write("									<li><button>\r\n");
      out.write("											<i class=\"ti-heart\"></i>\r\n");
      out.write("										</button></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"card-body\">\r\n");
      out.write("								<p>영칼로리</p>\r\n");
      out.write("								<h4 class=\"card-product__title\">\r\n");
      out.write("									<a href=\"single-product.html\">두툼 벌집껍데기(2인)</a>\r\n");
      out.write("								</h4>\r\n");
      out.write("								<p class=\"card-product__price\">7900원</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-md-6 col-lg-4 col-xl-3\">\r\n");
      out.write("						<div class=\"card text-center card-product\">\r\n");
      out.write("							<div class=\"card-product__img\">\r\n");
      out.write("								<img class=\"card-img\" src=\"/KITEN/resources/upload/a0d45d29-f030-41ed-b5c2-8a6e73a2feff_others_list1.jpg\" alt=\"\">\r\n");
      out.write("								<ul class=\"card-product__imgOverlay\">\r\n");
      out.write("									<li><button>\r\n");
      out.write("											<i class=\"ti-search\"></i>\r\n");
      out.write("										</button></li>\r\n");
      out.write("									<li><button>\r\n");
      out.write("											<i class=\"ti-shopping-cart\"></i>\r\n");
      out.write("										</button></li>\r\n");
      out.write("									<li><button>\r\n");
      out.write("											<i class=\"ti-heart\"></i>\r\n");
      out.write("										</button></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"card-body\">\r\n");
      out.write("								<p>상현달</p>\r\n");
      out.write("								<h4 class=\"card-product__title\">\r\n");
      out.write("									<a href=\"single-product.html\">굳지않는 가래떡과 쌀로만든 조청(1인)</a>\r\n");
      out.write("								</h4>\r\n");
      out.write("								<p class=\"card-product__price\">4900원</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-md-6 col-lg-4 col-xl-3\">\r\n");
      out.write("						<div class=\"card text-center card-product\">\r\n");
      out.write("							<div class=\"card-product__img\">\r\n");
      out.write("								<img class=\"card-img\" src=\"/KITEN/resources/upload/37363b51-faad-4651-b77e-82e838f3eda0_snackfood_list5.jpg\" alt=\"\">\r\n");
      out.write("								<ul class=\"card-product__imgOverlay\">\r\n");
      out.write("									<li><button>\r\n");
      out.write("											<i class=\"ti-search\"></i>\r\n");
      out.write("										</button></li>\r\n");
      out.write("									<li><button>\r\n");
      out.write("											<i class=\"ti-shopping-cart\"></i>\r\n");
      out.write("										</button></li>\r\n");
      out.write("									<li><button>\r\n");
      out.write("											<i class=\"ti-heart\"></i>\r\n");
      out.write("										</button></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"card-body\">\r\n");
      out.write("								<p>미니언즈</p>\r\n");
      out.write("								<h4 class=\"card-product__title\">\r\n");
      out.write("									<a href=\"single-product.html\">우정분식 물떡 어묵탕(2인)</a>\r\n");
      out.write("								</h4>\r\n");
      out.write("								<p class=\"card-product__price\">12900원</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-md-6 col-lg-4 col-xl-3\">\r\n");
      out.write("						<div class=\"card text-center card-product\">\r\n");
      out.write("							<div class=\"card-product__img\">\r\n");
      out.write("								<img class=\"card-img\" src=\"/KITEN/resources/upload/01a4b08f-cc8b-4335-8b21-26cf967dee37_japanese_list8.jpg\" alt=\"\">\r\n");
      out.write("								<ul class=\"card-product__imgOverlay\">\r\n");
      out.write("									<li><button>\r\n");
      out.write("											<i class=\"ti-search\"></i>\r\n");
      out.write("										</button></li>\r\n");
      out.write("									<li><button>\r\n");
      out.write("											<i class=\"ti-shopping-cart\"></i>\r\n");
      out.write("										</button></li>\r\n");
      out.write("									<li><button>\r\n");
      out.write("											<i class=\"ti-heart\"></i>\r\n");
      out.write("										</button></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"card-body\">\r\n");
      out.write("								<p>오사카맛도리</p>\r\n");
      out.write("								<h4 class=\"card-product__title\">\r\n");
      out.write("									<a href=\"single-product.html\">밀푀유나베(2인)</a>\r\n");
      out.write("								</h4>\r\n");
      out.write("								<p class=\"card-product__price\">12900원</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-md-6 col-lg-4 col-xl-3\">\r\n");
      out.write("						<div class=\"card text-center card-product\">\r\n");
      out.write("							<div class=\"card-product__img\">\r\n");
      out.write("								<img class=\"card-img\" src=\"/KITEN/resources/upload/f5b470cf-a2c4-4f1c-890d-171da6a58e2c_snackfood_list4.jpg\" alt=\"\">\r\n");
      out.write("								<ul class=\"card-product__imgOverlay\">\r\n");
      out.write("									<li><button>\r\n");
      out.write("											<i class=\"ti-search\"></i>\r\n");
      out.write("										</button></li>\r\n");
      out.write("									<li><button>\r\n");
      out.write("											<i class=\"ti-shopping-cart\"></i>\r\n");
      out.write("										</button></li>\r\n");
      out.write("									<li><button>\r\n");
      out.write("											<i class=\"ti-heart\"></i>\r\n");
      out.write("										</button></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"card-body\">\r\n");
      out.write("								<p>짱이네분식</p>\r\n");
      out.write("								<h4 class=\"card-product__title\">\r\n");
      out.write("									<a href=\"single-product.html\">매콤 양념 순대볶음(2인)</a>\r\n");
      out.write("								</h4>\r\n");
      out.write("								<p class=\"card-product__price\">11900원</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-md-6 col-lg-4 col-xl-3\">\r\n");
      out.write("						<div class=\"card text-center card-product\">\r\n");
      out.write("							<div class=\"card-product__img\">\r\n");
      out.write("								<img class=\"card-img\" src=\"/KITEN/resources/upload/23f9cef3-8370-460a-b06b-b8c955e5e5cd_snackfood_list3.jpg\" alt=\"\">\r\n");
      out.write("								<ul class=\"card-product__imgOverlay\">\r\n");
      out.write("									<li><button>\r\n");
      out.write("											<i class=\"ti-search\"></i>\r\n");
      out.write("										</button></li>\r\n");
      out.write("									<li><button>\r\n");
      out.write("											<i class=\"ti-shopping-cart\"></i>\r\n");
      out.write("										</button></li>\r\n");
      out.write("									<li><button>\r\n");
      out.write("											<i class=\"ti-heart\"></i>\r\n");
      out.write("										</button></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"card-body\">\r\n");
      out.write("								<p>짱이네분식</p>\r\n");
      out.write("								<h4 class=\"card-product__title\">\r\n");
      out.write("									<a href=\"#\">신림동식 백순대볶음(2인)</a>\r\n");
      out.write("								</h4>\r\n");
      out.write("								<p class=\"card-product__price\">11900원</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("		<!-- ================ trending product section end ================= -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- ================ offer section start ================= -->\r\n");
      out.write("		<section class=\"offer\" id=\"parallax-1\" data-anchor-target=\"#parallax-1\" data-300-top=\"background-position: 20px 30px\" data-top-bottom=\"background-position: 0 20px\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"col-xl-5\">\r\n");
      out.write("						<div class=\"offer__content text-center\">\r\n");
      out.write("					\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("		<!-- ================ offer section end ================= -->\r\n");
      out.write("\r\n");
      out.write("		<!-- ================ Best Selling item  carousel ================= -->\r\n");
      out.write("		<section class=\"section-margin calc-60px\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"section-intro pb-60px\">\r\n");
      out.write("					<p>제일 잘나감</p>\r\n");
      out.write("					<h2>\r\n");
      out.write("						베스트 <span class=\"section-intro__style\">랭킹</span>\r\n");
      out.write("					</h2>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"owl-carousel owl-theme\" id=\"bestSellerCarousel\">\r\n");
      out.write("					<div class=\"card text-center card-product\">\r\n");
      out.write("						<div class=\"card-product__img\">\r\n");
      out.write("							<img class=\"img-fluid\" src=\"/KITEN/resources/upload/24ce6650-b455-4d1a-a3c7-00eea6949173_southeastasian_list3.jpg\" alt=\"\">\r\n");
      out.write("							<ul class=\"card-product__imgOverlay\">\r\n");
      out.write("								<li><button>\r\n");
      out.write("										<i class=\"ti-search\"></i>\r\n");
      out.write("									</button></li>\r\n");
      out.write("								<li><button>\r\n");
      out.write("										<i class=\"ti-shopping-cart\"></i>\r\n");
      out.write("									</button></li>\r\n");
      out.write("								<li><button>\r\n");
      out.write("										<i class=\"ti-heart\"></i>\r\n");
      out.write("									</button></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"card-body\">\r\n");
      out.write("							<p>민수리아</p>\r\n");
      out.write("							<h4 class=\"card-product__title\">\r\n");
      out.write("								<a href=\"single-product.html\">소고기 볶음 국수</a>\r\n");
      out.write("							</h4>\r\n");
      out.write("							<p class=\"card-product__price\">13900원</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"card text-center card-product\">\r\n");
      out.write("						<div class=\"card-product__img\">\r\n");
      out.write("							<img class=\"img-fluid\" src=\"/KITEN/resources/upload/5106a6f9-1897-4e52-a206-c5bf30101f6e_western_list2.jpg\" alt=\"\">\r\n");
      out.write("							<ul class=\"card-product__imgOverlay\">\r\n");
      out.write("								<li><button>\r\n");
      out.write("										<i class=\"ti-search\"></i>\r\n");
      out.write("									</button></li>\r\n");
      out.write("								<li><button>\r\n");
      out.write("										<i class=\"ti-shopping-cart\"></i>\r\n");
      out.write("									</button></li>\r\n");
      out.write("								<li><button>\r\n");
      out.write("										<i class=\"ti-heart\"></i>\r\n");
      out.write("									</button></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"card-body\">\r\n");
      out.write("							<p>홀리이탈리아	</p>\r\n");
      out.write("							<h4 class=\"card-product__title\">\r\n");
      out.write("								<a href=\"single-product.html\">비프 볼로네제 파스타(2인)</a>\r\n");
      out.write("							</h4>\r\n");
      out.write("							<p class=\"card-product__price\">8900원</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"card text-center card-product\">\r\n");
      out.write("						<div class=\"card-product__img\">\r\n");
      out.write("							<img class=\"img-fluid\" src=\"/KITEN/resources/upload/e5419ed0-8525-49aa-8a0b-40decd1972f4_western_list1.jpg\" alt=\"\">\r\n");
      out.write("							<ul class=\"card-product__imgOverlay\">\r\n");
      out.write("								<li><button>\r\n");
      out.write("										<i class=\"ti-search\"></i>\r\n");
      out.write("									</button></li>\r\n");
      out.write("								<li><button>\r\n");
      out.write("										<i class=\"ti-shopping-cart\"></i>\r\n");
      out.write("									</button></li>\r\n");
      out.write("								<li><button>\r\n");
      out.write("										<i class=\"ti-heart\"></i>\r\n");
      out.write("									</button></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"card-body\">\r\n");
      out.write("							<p>비비쿡</p>\r\n");
      out.write("							<h4 class=\"card-product__title\">\r\n");
      out.write("								<a href=\"single-product.html\">불고기 퀘사디아(1-2인)</a>\r\n");
      out.write("							</h4>\r\n");
      out.write("							<p class=\"card-product__price\">8900원</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"card text-center card-product\">\r\n");
      out.write("						<div class=\"card-product__img\">\r\n");
      out.write("							<img class=\"img-fluid\" src=\"/KITEN/resources/upload/1b32b1d0-b306-4815-85df-083d47ad7e05_korean_list14.jpg\" alt=\"\">\r\n");
      out.write("							<ul class=\"card-product__imgOverlay\">\r\n");
      out.write("								<li><button>\r\n");
      out.write("										<i class=\"ti-search\"></i>\r\n");
      out.write("									</button></li>\r\n");
      out.write("								<li><button>\r\n");
      out.write("										<i class=\"ti-shopping-cart\"></i>\r\n");
      out.write("									</button></li>\r\n");
      out.write("								<li><button>\r\n");
      out.write("										<i class=\"ti-heart\"></i>\r\n");
      out.write("									</button></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"card-body\">\r\n");
      out.write("							<p>고기챔피언</p>\r\n");
      out.write("							<h4 class=\"card-product__title\">\r\n");
      out.write("								<a href=\"single-product.html\">훈제오리무쌈(2인)</a>\r\n");
      out.write("							</h4>\r\n");
      out.write("							<p class=\"card-product__price\">10900원</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"card text-center card-product\">\r\n");
      out.write("						<div class=\"card-product__img\">\r\n");
      out.write("							<img class=\"img-fluid\" src=\"/KITEN/resources/upload/13194688-7e54-40e6-b25d-d17ce6448f1a_western_list11.jpg\" alt=\"\">\r\n");
      out.write("							<ul class=\"card-product__imgOverlay\">\r\n");
      out.write("								<li><button>\r\n");
      out.write("										<i class=\"ti-search\"></i>\r\n");
      out.write("									</button></li>\r\n");
      out.write("								<li><button>\r\n");
      out.write("										<i class=\"ti-shopping-cart\"></i>\r\n");
      out.write("									</button></li>\r\n");
      out.write("								<li><button>\r\n");
      out.write("										<i class=\"ti-heart\"></i>\r\n");
      out.write("									</button></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"card-body\">\r\n");
      out.write("							<p>인프론트</p>\r\n");
      out.write("							<h4 class=\"card-product__title\">\r\n");
      out.write("								<a href=\"single-product.html\">나혼자 소고기 부채살 스테이크(1인)</a>\r\n");
      out.write("							</h4>\r\n");
      out.write("							<p class=\"card-product__price\">9900원</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"card text-center card-product\">\r\n");
      out.write("						<div class=\"card-product__img\">\r\n");
      out.write("							<img class=\"img-fluid\" src=\"/KITEN/resources/upload/fa70a7b1-8383-4c45-a544-7a95e9547e75_korean_list1.jpg\" alt=\"\">\r\n");
      out.write("							<ul class=\"card-product__imgOverlay\">\r\n");
      out.write("								<li><button>\r\n");
      out.write("										<i class=\"ti-search\"></i>\r\n");
      out.write("									</button></li>\r\n");
      out.write("								<li><button>\r\n");
      out.write("										<i class=\"ti-shopping-cart\"></i>\r\n");
      out.write("									</button></li>\r\n");
      out.write("								<li><button>\r\n");
      out.write("										<i class=\"ti-heart\"></i>\r\n");
      out.write("									</button></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"card-body\">\r\n");
      out.write("							<p>찌개의 제왕</p>\r\n");
      out.write("							<h4 class=\"card-product__title\">\r\n");
      out.write("								<a href=\"single-product.html\">된장찌개 & 캠핑 가니시 밀키트(3-4인)</a>\r\n");
      out.write("							</h4>\r\n");
      out.write("							<p class=\"card-product__price\">9900원</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"card text-center card-product\">\r\n");
      out.write("						<div class=\"card-product__img\">\r\n");
      out.write("							<img class=\"img-fluid\" src=\"/KITEN/resources/upload/08ac9a9d-b614-4222-b3be-87bc19eb6ec2_korean_list5.jpg\" alt=\"\">\r\n");
      out.write("							<ul class=\"card-product__imgOverlay\">\r\n");
      out.write("								<li><button>\r\n");
      out.write("										<i class=\"ti-search\"></i>\r\n");
      out.write("									</button></li>\r\n");
      out.write("								<li><button>\r\n");
      out.write("										<i class=\"ti-shopping-cart\"></i>\r\n");
      out.write("									</button></li>\r\n");
      out.write("								<li><button>\r\n");
      out.write("										<i class=\"ti-heart\"></i>\r\n");
      out.write("									</button></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"card-body\">\r\n");
      out.write("							<p>고기챔피언</p>\r\n");
      out.write("							<h4 class=\"card-product__title\">\r\n");
      out.write("								<a href=\"single-product.html\">매콤 쭈꾸미 삼겹살(2인)</a>\r\n");
      out.write("							</h4>\r\n");
      out.write("							<p class=\"card-product__price\">19900원</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"card text-center card-product\">\r\n");
      out.write("						<div class=\"card-product__img\">\r\n");
      out.write("							<img class=\"img-fluid\" src=\"/KITEN/resources/upload/e91bcf69-3e52-4a27-aa54-01774b2931d8_snackfood_list1.jpg\" alt=\"\">\r\n");
      out.write("							<ul class=\"card-product__imgOverlay\">\r\n");
      out.write("								<li><button>\r\n");
      out.write("										<i class=\"ti-search\"></i>\r\n");
      out.write("									</button></li>\r\n");
      out.write("								<li><button>\r\n");
      out.write("										<i class=\"ti-shopping-cart\"></i>\r\n");
      out.write("									</button></li>\r\n");
      out.write("								<li><button>\r\n");
      out.write("										<i class=\"ti-heart\"></i>\r\n");
      out.write("									</button></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"card-body\">\r\n");
      out.write("							<p>미니언즈</p>\r\n");
      out.write("							<h4 class=\"card-product__title\">\r\n");
      out.write("								<a href=\"single-product.html\">우정분식 아찔 떡볶잉(2인)</a>\r\n");
      out.write("							</h4>\r\n");
      out.write("							<p class=\"card-product__price\">15900원</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("		<!-- ================ Best Selling item  carousel end ================= -->\r\n");
      out.write("\r\n");
      out.write("		<!-- ================ Blog section start ================= -->\r\n");
      out.write("		\r\n");
      out.write("		<!-- ================ Blog section end ================= -->\r\n");
      out.write("\r\n");
      out.write("		<!-- ================ Subscribe section start ================= -->\r\n");
      out.write("		\r\n");
      out.write("		<!-- ================ Subscribe section end ================= -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</main>\r\n");
      out.write("\r\n");
      out.write("	<!--================ Start footer Area  =================-->\r\n");
      out.write("	<footer>\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"footer-area\">\r\n");
      out.write("						<hr></hr>\r\n");
      out.write("						<div class= \"ss\">\r\n");
      out.write("						<div class=\"s1\">\r\n");
      out.write("							<h4 class=\"footer_title large_title\">고객행복센터</h4>\r\n");
      out.write("							<table>\r\n");
      out.write("							\r\n");
      out.write("							<tr>\r\n");
      out.write("							<td class=\"nav-item\"><a class=\"button button-header\" href=\"#\">카톡 문의</a></td>\r\n");
      out.write("							<td><p>월~일요일 | 오전7시~ 오후6시 </p></td>\r\n");
      out.write("\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("							<td class=\"nav-item\"><a class=\"button button-header\" href=\"#\">개인 문의 </a></td>\r\n");
      out.write("							<td><p>365일 친절하게 문의 받겠습니다.</p></td>\r\n");
      out.write("\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("							<td class=\"nav-item\"><a class=\"button button-header\" href=\"#\">대량 문의</a></td>\r\n");
      out.write("						\r\n");
      out.write("							\r\n");
      out.write("							<td><p>월~일요일 | 오전9시~ 오후6시 </p></td>\r\n");
      out.write("							\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr></tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								\r\n");
      out.write("							<td><p> 비회원문의 : help @ kosmo.com</p></td>\r\n");
      out.write("\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("							<td><p> 비회원대량문의 : gift @ kosmo.com</p></td>\r\n");
      out.write("\r\n");
      out.write("							</tr>\r\n");
      out.write("							</table>\r\n");
      out.write("				\r\n");
      out.write("					</div>\r\n");
      out.write("						\r\n");
      out.write("						<div class=\"ml-40\">\r\n");
      out.write("\r\n");
      out.write("							<ul class=\"loginul\">\r\n");
      out.write("									<li class=\"loginli\"><a class=\"foot-link\" href=\"\">회사소개</a></li>\r\n");
      out.write("									<li class=\"loginli\"><a class=\"foot-link\" href=\"\">인재채용</a></li>\r\n");
      out.write("									<li class=\"loginli\"><a class=\"foot-link\" href=\"\">이용약관</a></li>\r\n");
      out.write("									<li class=\"loginli\"><a class=\"foot-link\" href=\"\">개인정보처리방침</a></li>\r\n");
      out.write("									<li class=\"loginli\"><a class=\"foot-link\" href=\"\">이용안내</a></li>\r\n");
      out.write("									<br></br>\r\n");
      out.write("									</ul>\r\n");
      out.write("							\r\n");
      out.write("								\r\n");
      out.write("								<p>법인명(상호) : 주식회사 키튼 | 사업자 등록번호 : 123-45-67890 사업자정보확인</p>\r\n");
      out.write("								<p>통신판매업 : 제 2022호-경기안양-00000호 | 개인정보보호책임자 : 강민수</p>\r\n");
      out.write("								<p>주소 : 서울특별시 어디구 어디로 133 101동 3층 | 대표이사 : 정지원</p>\r\n");
      out.write("								<p>채용문의 : job@kosmo.com</p>\r\n");
      out.write("								<p>팩스 : 000- 0000 - 0000\r\n");
      out.write("								\r\n");
      out.write("								</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"footer-bottom\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row d-flex\">\r\n");
      out.write("					<p class=\"col-lg-12 footer-text text-center\">\r\n");
      out.write("						<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("						Copyright &copy;\r\n");
      out.write("						<script>\r\n");
      out.write("							document.write(new Date().getFullYear());\r\n");
      out.write("						</script>\r\n");
      out.write("						All rights reserved | This template is made with <i class=\"fa fa-heart\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\r\n");
      out.write("						<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("					</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("	<!--================ End footer Area  =================-->\r\n");
      out.write("	\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("	//<![CDATA[\r\n");
      out.write("	$(document).ready(function(){\r\n");
      out.write("	$('.bxslider').bxSlider();\r\n");
      out.write("	});\r\n");
      out.write("	//]]>\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script src=\"");
      out.print(pjName);
      out.write("/resources/vendors/jquery/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.print(pjName);
      out.write("/resources/vendors/bootstrap/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.print(pjName);
      out.write("/resources/vendors/skrollr.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.print(pjName);
      out.write("/resources/vendors/owl-carousel/owl.carousel.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.print(pjName);
      out.write("/resources/vendors/nice-select/jquery.nice-select.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.print(pjName);
      out.write("/resources/vendors/jquery.ajaxchimp.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.print(pjName);
      out.write("/resources/vendors/mail-script.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.print(pjName);
      out.write("/resources/js/main.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.print(pjName);
      out.write("/resources/js/home.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
