/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2022-11-19 10:11:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mypage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1668852259111L));
    _jspx_dependants.put("jar:file:/C:/Users/1/Desktop/코딩/semiProject_KITEN/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/KITEN/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
 String pjName = "/KITEN"; 
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("<title>마이 페이지</title>\r\n");
      out.write("<link rel=\"icon\" href=\"");
      out.print(pjName);
      out.write("/resources/img/Fevicon.png\" type=\"image/png\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(pjName);
      out.write("/resources/vendors/bootstrap/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(pjName);
      out.write("/resources/vendors/fontawesome/css/all.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(pjName);
      out.write("/resources/vendors/themify-icons/themify-icons.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(pjName);
      out.write("/resources/vendors/linericon/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(pjName);
      out.write("/resources/vendors/owl-carousel/owl.theme.default.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(pjName);
      out.write("/resources/vendors/owl-carousel/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(pjName);
      out.write("/resources/vendors/nice-select/nice-select.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(pjName);
      out.write("/resources/vendors/nouislider/nouislider.min.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(pjName);
      out.write("/resources/css/stylej.css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("h4 {\r\n");
      out.write("	margin-bottom: 0;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!--================ Start Header Menu Area =================-->\r\n");
      out.write("	<header class=\"header_area\">\r\n");
      out.write("		<div class=\"main_menu\">\r\n");
      out.write("			<nav class=\"navbar navbar-expand-lg navbar-light\">\r\n");
      out.write("				<div class=\"container\">\r\n");
      out.write("					<a class=\"navbar-brand logo_h\" href=\"index.html\"><img src=\"");
      out.print(pjName);
      out.write("/resources/img/logo.png\" alt=\"\"></a>\r\n");
      out.write("					<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
      out.write("						aria-label=\"Toggle navigation\">\r\n");
      out.write("						<span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span>\r\n");
      out.write("					</button>\r\n");
      out.write("					<div class=\"collapse navbar-collapse offset\" id=\"navbarSupportedContent\">\r\n");
      out.write("						<ul class=\"nav navbar-nav menu_nav ml-auto mr-auto\">\r\n");
      out.write("							<li class=\"nav-item\"><a class=\"nav-link\" href=\"index.html\">Home</a></li>\r\n");
      out.write("							<li class=\"nav-item active submenu dropdown\"><a href=\"#\" class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">Shop</a>\r\n");
      out.write("								<ul class=\"dropdown-menu\">\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"category.html\">Shop Category</a></li>\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"single-product.html\">Product Details</a></li>\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"checkout.html\">Product Checkout</a></li>\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"confirmation.html\">Confirmation</a></li>\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"cart.html\">Shopping Cart</a></li>\r\n");
      out.write("								</ul></li>\r\n");
      out.write("							<li class=\"nav-item submenu dropdown\"><a href=\"#\" class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">Blog</a>\r\n");
      out.write("								<ul class=\"dropdown-menu\">\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"blog.html\">Blog</a></li>\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"single-blog.html\">Blog Details</a></li>\r\n");
      out.write("								</ul></li>\r\n");
      out.write("							<li class=\"nav-item submenu dropdown\"><a href=\"#\" class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">Pages</a>\r\n");
      out.write("								<ul class=\"dropdown-menu\">\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"login.html\">Login</a></li>\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"register.html\">Register</a></li>\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"tracking-order.html\">Tracking</a></li>\r\n");
      out.write("								</ul></li>\r\n");
      out.write("							<li class=\"nav-item\"><a class=\"nav-link\" href=\"contact.html\">Contact</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("\r\n");
      out.write("						<ul class=\"nav-shop\">\r\n");
      out.write("							<li class=\"nav-item\"><button>\r\n");
      out.write("									<i class=\"ti-search\"></i>\r\n");
      out.write("								</button></li>\r\n");
      out.write("							<li class=\"nav-item\"><button>\r\n");
      out.write("									<i class=\"ti-shopping-cart\"></i><span class=\"nav-shop__circle\">3</span>\r\n");
      out.write("								</button></li>\r\n");
      out.write("							<li class=\"nav-item\"><a class=\"button button-header\" href=\"#\">Buy Now</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</nav>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("	<!--================ End Header Menu Area =================-->\r\n");
      out.write("	<!-- ================ category section start ================= -->\r\n");
      out.write("	<section class=\"section-margin--small mb-5\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-xl-3 col-lg-4 col-md-5\">\r\n");
      out.write("					<h4 class=\"widget_title\">마이 페이지</h4>\r\n");
      out.write("					<div class=\"common-filter\">\r\n");
      out.write("						<ul class=\"list cat-list\">\r\n");
      out.write("							<li><a href=\"#\" class=\"d-flex justify-content-between\">\r\n");
      out.write("									<p>한식</p>\r\n");
      out.write("									<p>37</p>\r\n");
      out.write("							</a></li>\r\n");
      out.write("							<li><a href=\"#\" class=\"d-flex justify-content-between\">\r\n");
      out.write("									<p>분식</p>\r\n");
      out.write("									<p>24</p>\r\n");
      out.write("							</a></li>\r\n");
      out.write("							<li><a href=\"#\" class=\"d-flex justify-content-between\">\r\n");
      out.write("									<p>양식</p>\r\n");
      out.write("									<p>59</p>\r\n");
      out.write("							</a></li>\r\n");
      out.write("							<li><a href=\"#\" class=\"d-flex justify-content-between\">\r\n");
      out.write("									<p>중식</p>\r\n");
      out.write("									<p>29</p>\r\n");
      out.write("							</a></li>\r\n");
      out.write("							<li><a href=\"#\" class=\"d-flex justify-content-between\">\r\n");
      out.write("									<p>일식</p>\r\n");
      out.write("									<p>15</p>\r\n");
      out.write("							</a></li>\r\n");
      out.write("							<li><a href=\"#\" class=\"d-flex justify-content-between\">\r\n");
      out.write("									<p>동남아</p>\r\n");
      out.write("									<p>09</p>\r\n");
      out.write("							</a></li>\r\n");
      out.write("							<li><a href=\"#\" class=\"d-flex justify-content-between\">\r\n");
      out.write("									<p>그 외</p>\r\n");
      out.write("									<p>44</p>\r\n");
      out.write("							</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"br\"></div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-xl-9 col-lg-8 col-md-7\">\r\n");
      out.write("					<!-- Start Filter Bar -->\r\n");
      out.write("					<div class=\"filter-bar d-flex flex-wrap align-items-center\">\r\n");
      out.write("						<div class=\"sorting\">\r\n");
      out.write("							<select>\r\n");
      out.write("								<option value=\"1\">신상품순</option>\r\n");
      out.write("								<option value=\"1\">판매량순</option>\r\n");
      out.write("								<option value=\"1\">낮은 가격순</option>\r\n");
      out.write("								<option value=\"1\">높은 가격순</option>\r\n");
      out.write("							</select>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"sorting mr-auto\">\r\n");
      out.write("							<select>\r\n");
      out.write("								<option value=\"1\">6개 보기</option>\r\n");
      out.write("								<option value=\"1\">9개 보기</option>\r\n");
      out.write("								<option value=\"1\">12개 보기</option>\r\n");
      out.write("							</select>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div>\r\n");
      out.write("							<div class=\"input-group filter-bar-search\">\r\n");
      out.write("								<input type=\"text\" placeholder=\"검색어를 입력하세요\">\r\n");
      out.write("								<div class=\"input-group-append\">\r\n");
      out.write("									<button type=\"button\">\r\n");
      out.write("										<i class=\"ti-search\"></i>\r\n");
      out.write("									</button>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- End Filter Bar -->\r\n");
      out.write("					<!-- Start Best Seller -->\r\n");
      out.write("					<section class=\"lattest-product-area pb-40 category-list\">\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div class=\"col-md-6 col-lg-4\">\r\n");
      out.write("								<div class=\"card text-center card-product\">\r\n");
      out.write("									<div class=\"card-product__img\">\r\n");
      out.write("										<img class=\"card-img\" src=\"");
      out.print(pjName);
      out.write("/resources/img/product/product1.png\" alt=\"\">\r\n");
      out.write("										<ul class=\"card-product__imgOverlay\">\r\n");
      out.write("											<li><button>\r\n");
      out.write("													<i class=\"ti-search\"></i>\r\n");
      out.write("												</button></li>\r\n");
      out.write("											<li><button>\r\n");
      out.write("													<i class=\"ti-shopping-cart\"></i>\r\n");
      out.write("												</button></li>\r\n");
      out.write("											<li><button>\r\n");
      out.write("													<i class=\"ti-heart\"></i>\r\n");
      out.write("												</button></li>\r\n");
      out.write("										</ul>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"card-body\">\r\n");
      out.write("										<p>종갓집</p>\r\n");
      out.write("										<h4 class=\"card-product__title\">\r\n");
      out.write("											<a href=\"#\">장가 못 간 총각김치</a>\r\n");
      out.write("										</h4>\r\n");
      out.write("										<p class=\"card-product__price\">15,000원</p>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-md-6 col-lg-4\">\r\n");
      out.write("								<div class=\"card text-center card-product\">\r\n");
      out.write("									<div class=\"card-product__img\">\r\n");
      out.write("										<img class=\"card-img\" src=\"");
      out.print(pjName);
      out.write("/resources/img/product/product2.png\" alt=\"\">\r\n");
      out.write("										<ul class=\"card-product__imgOverlay\">\r\n");
      out.write("											<li><button>\r\n");
      out.write("													<i class=\"ti-search\"></i>\r\n");
      out.write("												</button></li>\r\n");
      out.write("											<li><button>\r\n");
      out.write("													<i class=\"ti-shopping-cart\"></i>\r\n");
      out.write("												</button></li>\r\n");
      out.write("											<li><button>\r\n");
      out.write("													<i class=\"ti-heart\"></i>\r\n");
      out.write("												</button></li>\r\n");
      out.write("										</ul>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"card-body\">\r\n");
      out.write("										<p>Beauty</p>\r\n");
      out.write("										<h4 class=\"card-product__title\">\r\n");
      out.write("											<a href=\"#\">Women Freshwash</a>\r\n");
      out.write("										</h4>\r\n");
      out.write("										<p class=\"card-product__price\">$150.00</p>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-md-6 col-lg-4\">\r\n");
      out.write("								<div class=\"card text-center card-product\">\r\n");
      out.write("									<div class=\"card-product__img\">\r\n");
      out.write("										<img class=\"card-img\" src=\"");
      out.print(pjName);
      out.write("/resources/img/product/product3.png\" alt=\"\">\r\n");
      out.write("										<ul class=\"card-product__imgOverlay\">\r\n");
      out.write("											<li><button>\r\n");
      out.write("													<i class=\"ti-search\"></i>\r\n");
      out.write("												</button></li>\r\n");
      out.write("											<li><button>\r\n");
      out.write("													<i class=\"ti-shopping-cart\"></i>\r\n");
      out.write("												</button></li>\r\n");
      out.write("											<li><button>\r\n");
      out.write("													<i class=\"ti-heart\"></i>\r\n");
      out.write("												</button></li>\r\n");
      out.write("										</ul>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"card-body\">\r\n");
      out.write("										<p>Decor</p>\r\n");
      out.write("										<h4 class=\"card-product__title\">\r\n");
      out.write("											<a href=\"#\">Room Flash Light</a>\r\n");
      out.write("										</h4>\r\n");
      out.write("										<p class=\"card-product__price\">$150.00</p>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-md-6 col-lg-4\">\r\n");
      out.write("								<div class=\"card text-center card-product\">\r\n");
      out.write("									<div class=\"card-product__img\">\r\n");
      out.write("										<img class=\"card-img\" src=\"");
      out.print(pjName);
      out.write("/resources/img/product/product4.png\" alt=\"\">\r\n");
      out.write("										<ul class=\"card-product__imgOverlay\">\r\n");
      out.write("											<li><button>\r\n");
      out.write("													<i class=\"ti-search\"></i>\r\n");
      out.write("												</button></li>\r\n");
      out.write("											<li><button>\r\n");
      out.write("													<i class=\"ti-shopping-cart\"></i>\r\n");
      out.write("												</button></li>\r\n");
      out.write("											<li><button>\r\n");
      out.write("													<i class=\"ti-heart\"></i>\r\n");
      out.write("												</button></li>\r\n");
      out.write("										</ul>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"card-body\">\r\n");
      out.write("										<p>Decor</p>\r\n");
      out.write("										<h4 class=\"card-product__title\">\r\n");
      out.write("											<a href=\"#\">Room Flash Light</a>\r\n");
      out.write("										</h4>\r\n");
      out.write("										<p class=\"card-product__price\">$150.00</p>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-md-6 col-lg-4\">\r\n");
      out.write("								<div class=\"card text-center card-product\">\r\n");
      out.write("									<div class=\"card-product__img\">\r\n");
      out.write("										<img class=\"card-img\" src=\"");
      out.print(pjName);
      out.write("/resources/img/product/product5.png\" alt=\"\">\r\n");
      out.write("										<ul class=\"card-product__imgOverlay\">\r\n");
      out.write("											<li><button>\r\n");
      out.write("													<i class=\"ti-search\"></i>\r\n");
      out.write("												</button></li>\r\n");
      out.write("											<li><button>\r\n");
      out.write("													<i class=\"ti-shopping-cart\"></i>\r\n");
      out.write("												</button></li>\r\n");
      out.write("											<li><button>\r\n");
      out.write("													<i class=\"ti-heart\"></i>\r\n");
      out.write("												</button></li>\r\n");
      out.write("										</ul>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"card-body\">\r\n");
      out.write("										<p>Accessories</p>\r\n");
      out.write("										<h4 class=\"card-product__title\">\r\n");
      out.write("											<a href=\"#\">Man Office Bag</a>\r\n");
      out.write("										</h4>\r\n");
      out.write("										<p class=\"card-product__price\">$150.00</p>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-md-6 col-lg-4\">\r\n");
      out.write("								<div class=\"card text-center card-product\">\r\n");
      out.write("									<div class=\"card-product__img\">\r\n");
      out.write("										<img class=\"card-img\" src=\"");
      out.print(pjName);
      out.write("/resources/img/product/product6.png\" alt=\"\">\r\n");
      out.write("										<ul class=\"card-product__imgOverlay\">\r\n");
      out.write("											<li><button>\r\n");
      out.write("													<i class=\"ti-search\"></i>\r\n");
      out.write("												</button></li>\r\n");
      out.write("											<li><button>\r\n");
      out.write("													<i class=\"ti-shopping-cart\"></i>\r\n");
      out.write("												</button></li>\r\n");
      out.write("											<li><button>\r\n");
      out.write("													<i class=\"ti-heart\"></i>\r\n");
      out.write("												</button></li>\r\n");
      out.write("										</ul>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"card-body\">\r\n");
      out.write("										<p>Kids Toy</p>\r\n");
      out.write("										<h4 class=\"card-product__title\">\r\n");
      out.write("											<a href=\"#\">Charging Car</a>\r\n");
      out.write("										</h4>\r\n");
      out.write("										<p class=\"card-product__price\">$150.00</p>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-md-6 col-lg-4\">\r\n");
      out.write("								<div class=\"card text-center card-product\">\r\n");
      out.write("									<div class=\"card-product__img\">\r\n");
      out.write("										<img class=\"card-img\" src=\"");
      out.print(pjName);
      out.write("/resources/img/product/product7.png\" alt=\"\">\r\n");
      out.write("										<ul class=\"card-product__imgOverlay\">\r\n");
      out.write("											<li><button>\r\n");
      out.write("													<i class=\"ti-search\"></i>\r\n");
      out.write("												</button></li>\r\n");
      out.write("											<li><button>\r\n");
      out.write("													<i class=\"ti-shopping-cart\"></i>\r\n");
      out.write("												</button></li>\r\n");
      out.write("											<li><button>\r\n");
      out.write("													<i class=\"ti-heart\"></i>\r\n");
      out.write("												</button></li>\r\n");
      out.write("										</ul>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"card-body\">\r\n");
      out.write("										<p>Accessories</p>\r\n");
      out.write("										<h4 class=\"card-product__title\">\r\n");
      out.write("											<a href=\"#\">Blutooth Speaker</a>\r\n");
      out.write("										</h4>\r\n");
      out.write("										<p class=\"card-product__price\">$150.00</p>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-md-6 col-lg-4\">\r\n");
      out.write("								<div class=\"card text-center card-product\">\r\n");
      out.write("									<div class=\"card-product__img\">\r\n");
      out.write("										<img class=\"card-img\" src=\"");
      out.print(pjName);
      out.write("/resources/img/product/product8.png\" alt=\"\">\r\n");
      out.write("										<ul class=\"card-product__imgOverlay\">\r\n");
      out.write("											<li><button>\r\n");
      out.write("													<i class=\"ti-search\"></i>\r\n");
      out.write("												</button></li>\r\n");
      out.write("											<li><button>\r\n");
      out.write("													<i class=\"ti-shopping-cart\"></i>\r\n");
      out.write("												</button></li>\r\n");
      out.write("											<li><button>\r\n");
      out.write("													<i class=\"ti-heart\"></i>\r\n");
      out.write("												</button></li>\r\n");
      out.write("										</ul>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"card-body\">\r\n");
      out.write("										<p>Kids Toy</p>\r\n");
      out.write("										<h4 class=\"card-product__title\">\r\n");
      out.write("											<a href=\"#\">Charging Car</a>\r\n");
      out.write("										</h4>\r\n");
      out.write("										<p class=\"card-product__price\">$150.00</p>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-md-6 col-lg-4\">\r\n");
      out.write("								<div class=\"card text-center card-product\">\r\n");
      out.write("									<div class=\"card-product__img\">\r\n");
      out.write("										<img class=\"card-img\" src=\"");
      out.print(pjName);
      out.write("/resources/img/product/product1.png\" alt=\"\">\r\n");
      out.write("										<ul class=\"card-product__imgOverlay\">\r\n");
      out.write("											<li><button>\r\n");
      out.write("													<i class=\"ti-search\"></i>\r\n");
      out.write("												</button></li>\r\n");
      out.write("											<li><button>\r\n");
      out.write("													<i class=\"ti-shopping-cart\"></i>\r\n");
      out.write("												</button></li>\r\n");
      out.write("											<li><button>\r\n");
      out.write("													<i class=\"ti-heart\"></i>\r\n");
      out.write("												</button></li>\r\n");
      out.write("										</ul>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"card-body\">\r\n");
      out.write("										<p>Accessories</p>\r\n");
      out.write("										<h4 class=\"card-product__title\">\r\n");
      out.write("											<a href=\"#\">Quartz Belt Watch</a>\r\n");
      out.write("										</h4>\r\n");
      out.write("										<p class=\"card-product__price\">$150.00</p>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</section>\r\n");
      out.write("					<!-- End Best Seller -->\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<!-- ================ category section end ================= -->\r\n");
      out.write("	<!--================ Start footer Area  =================-->\r\n");
      out.write("	<footer>\r\n");
      out.write("		<div class=\"footer-area\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row section_gap\">\r\n");
      out.write("					<div class=\"col-lg-3 col-md-6 col-sm-6\">\r\n");
      out.write("						<div class=\"single-footer-widget tp_widgets\">\r\n");
      out.write("							<h4 class=\"footer_title large_title\">Our Mission</h4>\r\n");
      out.write("							<p>So seed seed green that winged cattle in. Gathering thing made fly you're no divided deep moved us lan Gathering thing us land years living.</p>\r\n");
      out.write("							<p>So seed seed green that winged cattle in. Gathering thing made fly you're no divided deep moved</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"offset-lg-1 col-lg-2 col-md-6 col-sm-6\">\r\n");
      out.write("						<div class=\"single-footer-widget tp_widgets\">\r\n");
      out.write("							<h4 class=\"footer_title\">Quick Links</h4>\r\n");
      out.write("							<ul class=\"list\">\r\n");
      out.write("								<li><a href=\"#\">Home</a></li>\r\n");
      out.write("								<li><a href=\"#\">Shop</a></li>\r\n");
      out.write("								<li><a href=\"#\">Blog</a></li>\r\n");
      out.write("								<li><a href=\"#\">Product</a></li>\r\n");
      out.write("								<li><a href=\"#\">Brand</a></li>\r\n");
      out.write("								<li><a href=\"#\">Contact</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-lg-2 col-md-6 col-sm-6\">\r\n");
      out.write("						<div class=\"single-footer-widget instafeed\">\r\n");
      out.write("							<h4 class=\"footer_title\">Gallery</h4>\r\n");
      out.write("							<ul class=\"list instafeed d-flex flex-wrap\">\r\n");
      out.write("								<li><img src=\"");
      out.print(pjName);
      out.write("/resources/img/gallery/r1.jpg\" alt=\"\"></li>\r\n");
      out.write("								<li><img src=\"");
      out.print(pjName);
      out.write("/resources/img/gallery/r2.jpg\" alt=\"\"></li>\r\n");
      out.write("								<li><img src=\"");
      out.print(pjName);
      out.write("/resources/img/gallery/r3.jpg\" alt=\"\"></li>\r\n");
      out.write("								<li><img src=\"");
      out.print(pjName);
      out.write("/resources/img/gallery/r5.jpg\" alt=\"\"></li>\r\n");
      out.write("								<li><img src=\"");
      out.print(pjName);
      out.write("/resources/img/gallery/r7.jpg\" alt=\"\"></li>\r\n");
      out.write("								<li><img src=\"");
      out.print(pjName);
      out.write("/resources/img/gallery/r8.jpg\" alt=\"\"></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"offset-lg-1 col-lg-3 col-md-6 col-sm-6\">\r\n");
      out.write("						<div class=\"single-footer-widget tp_widgets\">\r\n");
      out.write("							<h4 class=\"footer_title\">Contact Us</h4>\r\n");
      out.write("							<div class=\"ml-40\">\r\n");
      out.write("								<p class=\"sm-head\">\r\n");
      out.write("									<span class=\"fa fa-location-arrow\"></span> Head Office\r\n");
      out.write("								</p>\r\n");
      out.write("								<p>123, Main Street, Your City</p>\r\n");
      out.write("\r\n");
      out.write("								<p class=\"sm-head\">\r\n");
      out.write("									<span class=\"fa fa-phone\"></span> Phone Number\r\n");
      out.write("								</p>\r\n");
      out.write("								<p>\r\n");
      out.write("									+123 456 7890 <br> +123 456 7890\r\n");
      out.write("								</p>\r\n");
      out.write("\r\n");
      out.write("								<p class=\"sm-head\">\r\n");
      out.write("									<span class=\"fa fa-envelope\"></span> Email\r\n");
      out.write("								</p>\r\n");
      out.write("								<p>\r\n");
      out.write("									free@infoexample.com <br> www.infoexample.com\r\n");
      out.write("								</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"footer-bottom\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row d-flex\">\r\n");
      out.write("					<p class=\"col-lg-12 footer-text text-center\">\r\n");
      out.write("						<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("						Copyright &copy;\r\n");
      out.write("						<script>document.write(new Date().getFullYear());</script>\r\n");
      out.write("						All rights reserved | This template is made with <i class=\"fa fa-heart\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\r\n");
      out.write("						<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("					</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("	<!--================ End footer Area  =================-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script src=\"");
      out.print(pjName);
      out.write("/resources/vendors/jquery/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.print(pjName);
      out.write("/resources/vendors/bootstrap/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.print(pjName);
      out.write("/resources/vendors/skrollr.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.print(pjName);
      out.write("/resources/vendors/owl-carousel/owl.carousel.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.print(pjName);
      out.write("/resources/vendors/nice-select/jquery.nice-select.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.print(pjName);
      out.write("/resources/vendors/nouislider/nouislider.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.print(pjName);
      out.write("/resources/vendors/jquery.ajaxchimp.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.print(pjName);
      out.write("/resources/vendors/mail-script.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.print(pjName);
      out.write("/resources/js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
