/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2022-11-18 07:39:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class single_002dproduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	String pjName = "/KITEN";

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("<title>Aroma Shop - Product Details</title>\r\n");
      out.write("<link rel=\"icon\" href=\"");
      out.print(pjName);
      out.write("/resources/img/Fevicon.png\" type=\"image/png\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(pjName);
      out.write("/resources/vendors/bootstrap/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(pjName);
      out.write("/resources/vendors/fontawesome/css/all.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(pjName);
      out.write("/resources/vendors/themify-icons/themify-icons.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(pjName);
      out.write("/resources/vendors/linericon/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(pjName);
      out.write("/resources/vendors/nice-select/nice-select.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(pjName);
      out.write("/resources/vendors/owl-carousel/owl.theme.default.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(pjName);
      out.write("/resources/vendors/owl-carousel/owl.carousel.min.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(pjName);
      out.write("/resources/css/stylem.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!--================ Start Header Menu Area =================-->\r\n");
      out.write("	<header class=\"header_area\">\r\n");
      out.write("		<div class=\"main_menu\">\r\n");
      out.write("			<nav class=\"navbar navbar-expand-lg navbar-light\">\r\n");
      out.write("				<div class=\"container\">\r\n");
      out.write("					<a class=\"navbar-brand logo_h\" href=\"index.html\"><img src=\"");
      out.print(pjName);
      out.write("/resources/img/logo.png\" alt=\"\"></a>\r\n");
      out.write("					<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
      out.write("						aria-label=\"Toggle navigation\">\r\n");
      out.write("						<span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span>\r\n");
      out.write("					</button>\r\n");
      out.write("					<div class=\"collapse navbar-collapse offset\" id=\"navbarSupportedContent\">\r\n");
      out.write("						<ul class=\"nav navbar-nav menu_nav ml-auto mr-auto\">\r\n");
      out.write("							<li class=\"nav-item\"><a class=\"nav-link\" href=\"index.html\">Home</a></li>\r\n");
      out.write("							<li class=\"nav-item active submenu dropdown\"><a href=\"#\" class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">Shop</a>\r\n");
      out.write("								<ul class=\"dropdown-menu\">\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"category.html\">Shop Category</a></li>\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"single-product.html\">Product Details</a></li>\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"checkout.html\">Product Checkout</a></li>\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"confirmation.html\">Confirmation</a></li>\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"cart.html\">Shopping Cart</a></li>\r\n");
      out.write("								</ul></li>\r\n");
      out.write("							<li class=\"nav-item submenu dropdown\"><a href=\"#\" class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">Blog</a>\r\n");
      out.write("								<ul class=\"dropdown-menu\">\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"blog.html\">Blog</a></li>\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"single-blog.html\">Blog Details</a></li>\r\n");
      out.write("								</ul></li>\r\n");
      out.write("							<li class=\"nav-item submenu dropdown\"><a href=\"#\" class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">Pages</a>\r\n");
      out.write("								<ul class=\"dropdown-menu\">\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"login.html\">Login</a></li>\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"register.html\">Register</a></li>\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"tracking-order.html\">Tracking</a></li>\r\n");
      out.write("								</ul></li>\r\n");
      out.write("							<li class=\"nav-item\"><a class=\"nav-link\" href=\"contact.html\">Contact</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("\r\n");
      out.write("						<ul class=\"nav-shop\">\r\n");
      out.write("							<li class=\"nav-item\"><button>\r\n");
      out.write("									<i class=\"ti-search\"></i>\r\n");
      out.write("								</button></li>\r\n");
      out.write("							<li class=\"nav-item\"><button>\r\n");
      out.write("									<i class=\"ti-shopping-cart\"></i><span class=\"nav-shop__circle\">3</span>\r\n");
      out.write("								</button></li>\r\n");
      out.write("							<li class=\"nav-item\"><a class=\"button button-header\" href=\"#\">Buy Now</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</nav>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("	<!--================ End Header Menu Area =================-->\r\n");
      out.write("\r\n");
      out.write("	<!-- ================ start banner area ================= -->\r\n");
      out.write("	\r\n");
      out.write("	<!-- ================ end banner area ================= -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!--================Single Product Area =================-->\r\n");
      out.write("	<div class=\"product_image_area\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row s_product_inner\">\r\n");
      out.write("				<div class=\"col-lg-6\">\r\n");
      out.write("					<div class=\"owl-carousel owl-theme s_Product_carousel\">\r\n");
      out.write("						<div class=\"single-prd-item\">\r\n");
      out.write("							<img class=\"img-fluid\" src=\"");
      out.print(pjName);
      out.write("/resources/img/category/s-p1.jpg\" alt=\"\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- <div class=\"single-prd-item\">\r\n");
      out.write("							<img class=\"img-fluid\" src=\"");
      out.print(pjName);
      out.write("/resources/img/category/s-p1.jpg\" alt=\"\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"single-prd-item\">\r\n");
      out.write("							<img class=\"img-fluid\" src=\"");
      out.print(pjName);
      out.write("/resources/img/category/s-p1.jpg\" alt=\"\">\r\n");
      out.write("						</div> -->\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-5 offset-lg-1\">\r\n");
      out.write("					<div class=\"s_product_text\">\r\n");
      out.write("						<h3>멋진 시계</h3>\r\n");
      out.write("						<h2>35,000원</h2>\r\n");
      out.write("						<ul class=\"list\">\r\n");
      out.write("							<li><a class=\"active\" href=\"#\"><span>상품이름</span> : 맛있는 시계</a></li><br/>\r\n");
      out.write("							<li><a class=\"active\" href=\"#\"><span>카테고리</span> : 시계</a></li><br/>\r\n");
      out.write("							<li><a class=\"active\" href=\"#\"><span>포장타입</span> : 비닐</a></li><br/>\r\n");
      out.write("							<li><a class=\"active\" href=\"#\"><span>판매단위</span> : 1EA</a></li><br/>\r\n");
      out.write("							<li><a class=\"active\" href=\"#\"><span>중량</span> : 150kg</a></li><br/>\r\n");
      out.write("							<li><a class=\"active\" href=\"#\"><span>원산지</span> : 스위스</a></li><br/>\r\n");
      out.write("						</ul>\r\n");
      out.write("						<p>엄청나게 맛있는 시계입니다. 다들 포장뜯고 전자레인지 30분 돌려서 드시길 바랍니다. 화이팅 합시다!</p>\r\n");
      out.write("						<div class=\"product_count\">\r\n");
      out.write("							<label for=\"qty\">수량:</label>\r\n");
      out.write("							<button onclick=\"var result = document.getElementById('sst'); var sst = result.value; if( !isNaN( sst ) &amp;&amp; sst > 0 ) result.value--;return false;\" class=\"reduced items-count\"\r\n");
      out.write("								type=\"button\">\r\n");
      out.write("								▼\r\n");
      out.write("							</button>\r\n");
      out.write("							<input type=\"text\" name=\"qty\" id=\"sst\" size=\"2\" maxlength=\"12\" value=\"1\" title=\"Quantity:\" class=\"input-text qty\">\r\n");
      out.write("							<button onclick=\"var result = document.getElementById('sst'); var sst = result.value; if( !isNaN( sst )) result.value++;return false;\" class=\"increase items-count\" type=\"button\">\r\n");
      out.write("								▲\r\n");
      out.write("							</button>\r\n");
      out.write("							\r\n");
      out.write("							\r\n");
      out.write("							\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"card_area d-flex align-items-center\">\r\n");
      out.write("						<a></a>\r\n");
      out.write("						 <a class=\"icon_btn\" href=\"#\"><i class=\"lnr lnr lnr-heart\"></i></a>\r\n");
      out.write("						 <a class=\"button primary-btn\" href=\"#\">구매하기</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!--================End Single Product Area =================-->\r\n");
      out.write("\r\n");
      out.write("	<!--================Product Description Area =================-->\r\n");
      out.write("	<section class=\"product_description_area\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<ul class=\"nav nav-tabs\" id=\"myTab\" role=\"tablist\">\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" id=\"home-tab\" data-toggle=\"tab\" href=\"#home\" role=\"tab\" aria-controls=\"home\" aria-selected=\"true\">상세 설명</a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" id=\"profile-tab\" data-toggle=\"tab\" href=\"#profile\" role=\"tab\" aria-controls=\"profile\" aria-selected=\"false\">상품 정보</a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" id=\"contact-tab\" data-toggle=\"tab\" href=\"#review\" role=\"tab\" aria-controls=\"contact\" aria-selected=\"false\">상품 후기</a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link active\" id=\"review-tab\" data-toggle=\"tab\" href=\"#contact\" role=\"tab\" aria-controls=\"review\" aria-selected=\"false\">상품 문의</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			<div class=\"tab-content\" id=\"myTabContent\">\r\n");
      out.write("				<div class=\"tab-pane fade\" id=\"home\" role=\"tabpanel\" aria-labelledby=\"home-tab\">\r\n");
      out.write("					<p>너무너무 맛잇는 시계..</p>\r\n");
      out.write("					<p>매우 매우 멋진 시계 입니다.</p>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"tab-pane fade\" id=\"profile\" role=\"tabpanel\" aria-labelledby=\"profile-tab\">\r\n");
      out.write("					<div class=\"table-responsive\">\r\n");
      out.write("						<table class=\"table\">\r\n");
      out.write("							<tbody>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td>\r\n");
      out.write("										<h5>판매자</h5>\r\n");
      out.write("									</td>\r\n");
      out.write("									<td>\r\n");
      out.write("										<h5>삼진어묵</h5>\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td>\r\n");
      out.write("										<h5>포장타입</h5>\r\n");
      out.write("									</td>\r\n");
      out.write("									<td>\r\n");
      out.write("										<h5>냉장(종이포장)</h5>\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td>\r\n");
      out.write("										<h5>판매세트</h5>\r\n");
      out.write("									</td>\r\n");
      out.write("									<td>\r\n");
      out.write("										<h5>1세트</h5>\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td>\r\n");
      out.write("										<h5>중량/용량</h5>\r\n");
      out.write("									</td>\r\n");
      out.write("									<td>\r\n");
      out.write("										<h5>280*2개입</h5>\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td>\r\n");
      out.write("										<h5>원산지</h5>\r\n");
      out.write("									</td>\r\n");
      out.write("									<td>\r\n");
      out.write("										<h5>국내산</h5>\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td>\r\n");
      out.write("										<h5>알레르기정보</h5>\r\n");
      out.write("									</td>\r\n");
      out.write("									<td>\r\n");
      out.write("										<h5>밀/대게/함유</h5>\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								\r\n");
      out.write("							</tbody>\r\n");
      out.write("						</table>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"tab-pane fade show active\" id=\"review\" role=\"tabpanel\" aria-labelledby=\"review-tab\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col-lg-6\">\r\n");
      out.write("							<div class=\"row total_rate\">\r\n");
      out.write("								<div class=\"col-6\">\r\n");
      out.write("									<div class=\"box_total\">\r\n");
      out.write("										<h5>평점</h5>\r\n");
      out.write("										<h4>4.0</h4>\r\n");
      out.write("										<h6>리뷰 갯수</h6>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"col-6\">\r\n");
      out.write("									<div class=\"rating_list\">\r\n");
      out.write("										<h3>리뷰 평점</h3>\r\n");
      out.write("										<ul class=\"list\">\r\n");
      out.write("											<li><a href=\"#\">5 점 <i class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i> 01\r\n");
      out.write("											</a></li>\r\n");
      out.write("											<li><a href=\"#\">4 점 <i class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i> 01\r\n");
      out.write("											</a></li>\r\n");
      out.write("											<li><a href=\"#\">3 점 <i class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i> 01\r\n");
      out.write("											</a></li>\r\n");
      out.write("											<li><a href=\"#\">2 점 <i class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i> 01\r\n");
      out.write("											</a></li>\r\n");
      out.write("											<li><a href=\"#\">1 점 <i class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i> 01\r\n");
      out.write("											</a></li>\r\n");
      out.write("										</ul>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"review_list\">\r\n");
      out.write("								<div class=\"review_item\">\r\n");
      out.write("									<div class=\"media\">\r\n");
      out.write("										<div class=\"d-flex\">\r\n");
      out.write("											<img src=\"");
      out.print(pjName);
      out.write("/resources/img/product/review-1.png\" alt=\"\">\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"media-body\">\r\n");
      out.write("											<h4>오경호</h4>\r\n");
      out.write("											<i class=\"fa fa-star\"></i> <i class=\"fa fa-star\"></i> <i class=\"fa fa-star\"></i> <i class=\"fa fa-star\"></i> <i class=\"fa fa-star\"></i>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<p>너무너무 맛있어요. 시계가 달아요</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"review_item\">\r\n");
      out.write("									<div class=\"media\">\r\n");
      out.write("										<div class=\"d-flex\">\r\n");
      out.write("											<img src=\"");
      out.print(pjName);
      out.write("/resources/img/product/review-2.png\" alt=\"\">\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"media-body\">\r\n");
      out.write("											<h4>강민수</h4>\r\n");
      out.write("											<i class=\"fa fa-star\"></i> <i class=\"fa fa-star\"></i> <i class=\"fa fa-star\"></i> <i class=\"fa fa-star\"></i> <i class=\"fa fa-star\"></i>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<p>제가 먹어본 시계 중에선 최고입니다 ^^ 항상 애용할게요 ㅋ </p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"review_item\">\r\n");
      out.write("									<div class=\"media\">\r\n");
      out.write("										<div class=\"d-flex\">\r\n");
      out.write("											<img src=\"");
      out.print(pjName);
      out.write("/resources/img/product/review-3.png\" alt=\"\">\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"media-body\">\r\n");
      out.write("											<h4>김상현</h4>\r\n");
      out.write("											<i class=\"fa fa-star\"></i> <i class=\"fa fa-star\"></i> <i class=\"fa fa-star\"></i> <i class=\"fa fa-star\"></i> <i class=\"fa fa-star\"></i>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<p>시계가 좋아 좋아 좋아 주아 조아 쥬황 주화 주 주 주 주 주 주 주 주 </p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-lg-6\">\r\n");
      out.write("							<div class=\"review_box\">\r\n");
      out.write("								<h4>리뷰 쓰기</h4>\r\n");
      out.write("								<p>당신의 별점:</p>\r\n");
      out.write("								<ul class=\"list\">\r\n");
      out.write("									<li><a href=\"#\"><i class=\"fa fa-star\"></i></a></li>\r\n");
      out.write("									<li><a href=\"#\"><i class=\"fa fa-star\"></i></a></li>\r\n");
      out.write("									<li><a href=\"#\"><i class=\"fa fa-star\"></i></a></li>\r\n");
      out.write("									<li><a href=\"#\"><i class=\"fa fa-star\"></i></a></li>\r\n");
      out.write("									<li><a href=\"#\"><i class=\"fa fa-star\"></i></a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("								<p>별점 주기</p>\r\n");
      out.write("								<form action=\"#/\" class=\"form-contact form-review mt-3\">\r\n");
      out.write("									<div class=\"form-group\">\r\n");
      out.write("										<input class=\"form-control\" name=\"name\" type=\"text\" placeholder=\"이름을 입력하세요.\" required>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"form-group\">\r\n");
      out.write("										<input class=\"form-control\" name=\"email\" type=\"email\" placeholder=\"이메일을 입력하세요.\" required>\r\n");
      out.write("									</div>\r\n");
      out.write("									\r\n");
      out.write("									<div class=\"form-group\">\r\n");
      out.write("										<textarea class=\"form-control different-control w-100\" name=\"textarea\" id=\"textarea\" cols=\"30\" rows=\"5\" placeholder=\"메세지를 입력하세요.\"></textarea>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"form-group text-center text-md-right mt-3\">\r\n");
      out.write("										<button type=\"submit\" class=\"button button--active button-review\">글 쓰기</button>\r\n");
      out.write("									</div>\r\n");
      out.write("								</form>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"tab-pane fade\" id=\"contact\" role=\"tabpanel\" aria-labelledby=\"contact-tab\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col-lg-6\">\r\n");
      out.write("							<div class=\"comment_list\">\r\n");
      out.write("								<div class=\"review_item\">\r\n");
      out.write("									<div class=\"media\">\r\n");
      out.write("										<div class=\"d-flex\">\r\n");
      out.write("											<img src=\"");
      out.print(pjName);
      out.write("/resources/img/product/review-1.png\" alt=\"\">\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"media-body\">\r\n");
      out.write("											<h4>오경호</h4>\r\n");
      out.write("											<h5>2022년 09월12일</h5>\r\n");
      out.write("											<a class=\"reply_btn\" href=\"#\">답글</a>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<p>혹시 이 시계를 먹으면 복통이 일어날 수 있을까요?</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"review_item reply\">\r\n");
      out.write("									<div class=\"media\">\r\n");
      out.write("										<div class=\"d-flex\">\r\n");
      out.write("											<img src=\"");
      out.print(pjName);
      out.write("/resources/img/product/review-2.png\" alt=\"\">\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"media-body\">\r\n");
      out.write("											<h4>강민수</h4>\r\n");
      out.write("											<h5>2022년09월13일</h5>\r\n");
      out.write("											<a class=\"reply_btn\" href=\"#\">답글</a>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<p>아니요 절대 그럴일 없습니다.</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"review_item\">\r\n");
      out.write("									<div class=\"media\">\r\n");
      out.write("										<div class=\"d-flex\">\r\n");
      out.write("											<img src=\"");
      out.print(pjName);
      out.write("/resources/img/product/review-3.png\" alt=\"\">\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"media-body\">\r\n");
      out.write("											<h4>김상현</h4>\r\n");
      out.write("											<h5>2022년 09월 10일</h5>\r\n");
      out.write("											<a class=\"reply_btn\" href=\"#\">답글</a>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<p>시계가 맛있어서 대량으로 구매를 원합니다. 1000000개 구입 가능한가요?</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-lg-6\">\r\n");
      out.write("							<div class=\"review_box\">\r\n");
      out.write("								<h4>문의 달기</h4>\r\n");
      out.write("								<form class=\"row contact_form\" action=\"contact_process.php\" method=\"post\" id=\"contactForm\" novalidate=\"novalidate\">\r\n");
      out.write("									<div class=\"col-md-12\">\r\n");
      out.write("										<div class=\"form-group\">\r\n");
      out.write("											<input type=\"text\" class=\"form-control\" id=\"name\" name=\"name\" placeholder=\"이름을 입력하세요.\">\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"col-md-12\">\r\n");
      out.write("										<div class=\"form-group\">\r\n");
      out.write("											<input type=\"email\" class=\"form-control\" id=\"email\" name=\"email\" placeholder=\"이메일을 입력하세요.\">\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"col-md-12\">\r\n");
      out.write("										<div class=\"form-group\">\r\n");
      out.write("											<input type=\"text\" class=\"form-control\" id=\"number\" name=\"number\" placeholder=\"핸드폰을 입력하세요.\">\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"col-md-12\">\r\n");
      out.write("										<div class=\"form-group\">\r\n");
      out.write("											<textarea class=\"form-control\" name=\"message\" id=\"message\" rows=\"1\" placeholder=\"내용을 입력하세요.\"></textarea>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"col-md-12 text-right\">\r\n");
      out.write("										<button type=\"submit\" value=\"submit\" class=\"btn primary-btn\"> 글쓰기</button>\r\n");
      out.write("									</div>\r\n");
      out.write("								</form>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<!--================End Product Description Area =================-->\r\n");
      out.write("\r\n");
      out.write("	<!--================ Start related Product area =================-->\r\n");
      out.write("	\r\n");
      out.write("	<!--================ end related Product area =================-->\r\n");
      out.write("\r\n");
      out.write("	<!--================ Start footer Area  =================-->\r\n");
      out.write("	<footer>\r\n");
      out.write("		<div class=\"footer-area footer-only\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row section_gap\">\r\n");
      out.write("					<div class=\"col-lg-3 col-md-6 col-sm-6\">\r\n");
      out.write("						<div class=\"single-footer-widget tp_widgets \">\r\n");
      out.write("							<h4 class=\"footer_title large_title\">Our Mission</h4>\r\n");
      out.write("							<p>So seed seed green that winged cattle in. Gathering thing made fly you're no divided deep moved us lan Gathering thing us land years living.</p>\r\n");
      out.write("							<p>So seed seed green that winged cattle in. Gathering thing made fly you're no divided deep moved</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"offset-lg-1 col-lg-2 col-md-6 col-sm-6\">\r\n");
      out.write("						<div class=\"single-footer-widget tp_widgets\">\r\n");
      out.write("							<h4 class=\"footer_title\">Quick Links</h4>\r\n");
      out.write("							<ul class=\"list\">\r\n");
      out.write("								<li><a href=\"#\">Home</a></li>\r\n");
      out.write("								<li><a href=\"#\">Shop</a></li>\r\n");
      out.write("								<li><a href=\"#\">Blog</a></li>\r\n");
      out.write("								<li><a href=\"#\">Product</a></li>\r\n");
      out.write("								<li><a href=\"#\">Brand</a></li>\r\n");
      out.write("								<li><a href=\"#\">Contact</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-lg-2 col-md-6 col-sm-6\">\r\n");
      out.write("						<div class=\"single-footer-widget instafeed\">\r\n");
      out.write("							<h4 class=\"footer_title\">Gallery</h4>\r\n");
      out.write("							<ul class=\"list instafeed d-flex flex-wrap\">\r\n");
      out.write("								<li><img src=\"");
      out.print(pjName);
      out.write("/resources/img/gallery/r1.jpg\" alt=\"\"></li>\r\n");
      out.write("								<li><img src=\"");
      out.print(pjName);
      out.write("/resources/img/gallery/r2.jpg\" alt=\"\"></li>\r\n");
      out.write("								<li><img src=\"");
      out.print(pjName);
      out.write("/resources/img/gallery/r3.jpg\" alt=\"\"></li>\r\n");
      out.write("								<li><img src=\"");
      out.print(pjName);
      out.write("/resources/img/gallery/r5.jpg\" alt=\"\"></li>\r\n");
      out.write("								<li><img src=\"");
      out.print(pjName);
      out.write("/resources/img/gallery/r7.jpg\" alt=\"\"></li>\r\n");
      out.write("								<li><img src=\"");
      out.print(pjName);
      out.write("/resources/img/gallery/r8.jpg\" alt=\"\"></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"offset-lg-1 col-lg-3 col-md-6 col-sm-6\">\r\n");
      out.write("						<div class=\"single-footer-widget tp_widgets\">\r\n");
      out.write("							<h4 class=\"footer_title\">Contact Us</h4>\r\n");
      out.write("							<div class=\"ml-40\">\r\n");
      out.write("								<p class=\"sm-head\">\r\n");
      out.write("									<span class=\"fa fa-location-arrow\"></span> Head Office\r\n");
      out.write("								</p>\r\n");
      out.write("								<p>123, Main Street, Your City</p>\r\n");
      out.write("\r\n");
      out.write("								<p class=\"sm-head\">\r\n");
      out.write("									<span class=\"fa fa-phone\"></span> Phone Number\r\n");
      out.write("								</p>\r\n");
      out.write("								<p>\r\n");
      out.write("									+123 456 7890 <br> +123 456 7890\r\n");
      out.write("								</p>\r\n");
      out.write("\r\n");
      out.write("								<p class=\"sm-head\">\r\n");
      out.write("									<span class=\"fa fa-envelope\"></span> Email\r\n");
      out.write("								</p>\r\n");
      out.write("								<p>\r\n");
      out.write("									free@infoexample.com <br> www.infoexample.com\r\n");
      out.write("								</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"footer-bottom\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row d-flex\">\r\n");
      out.write("					<p class=\"col-lg-12 footer-text text-center\">\r\n");
      out.write("						<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("						Copyright &copy;\r\n");
      out.write("						<script>document.write(new Date().getFullYear());</script>\r\n");
      out.write("						All rights reserved | This template is made with <i class=\"fa fa-heart\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\r\n");
      out.write("						<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("					</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("	<!--================ End footer Area  =================-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script src=\"");
      out.print(pjName);
      out.write("/resources/vendors/jquery/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.print(pjName);
      out.write("/resources/vendors/bootstrap/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.print(pjName);
      out.write("/resources/vendors/skrollr.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.print(pjName);
      out.write("/resources/vendors/owl-carousel/owl.carousel.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.print(pjName);
      out.write("/resources/vendors/nice-select/jquery.nice-select.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.print(pjName);
      out.write("/resources/vendors/jquery.ajaxchimp.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.print(pjName);
      out.write("/resources/vendors/mail-script.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.print(pjName);
      out.write("/resources/js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
